#pandas

In [4]:
 import pandas as pd

In [5]:
# file read and write operations

In [6]:
pd.read_csv

<function pandas.io.parsers.readers.read_csv(filepath_or_buffer: 'FilePathOrBuffer', sep=<no_default>, delimiter=None, header='infer', names=<no_default>, index_col=None, usecols=None, squeeze=False, prefix=<no_default>, mangle_dupe_cols=True, dtype: 'DtypeArg | None' = None, engine=None, converters=None, true_values=None, false_values=None, skipinitialspace=False, skiprows=None, skipfooter=0, nrows=None, na_values=None, keep_default_na=True, na_filter=True, verbose=False, skip_blank_lines=True, parse_dates=False, infer_datetime_format=False, keep_date_col=False, date_parser=None, dayfirst=False, cache_dates=True, iterator=False, chunksize=None, compression='infer', thousands=None, decimal: 'str' = '.', lineterminator=None, quotechar='"', quoting=0, doublequote=True, escapechar=None, comment=None, encoding=None, encoding_errors: 'str | None' = 'strict', dialect=None, error_bad_lines=None, warn_bad_lines=None, on_bad_lines=None, delim_whitespace=False, low_memory=True, memory_map=False, float_precision=None, storage_options: 'StorageOptions' = None)>

In [7]:
# pandas takes first row as to column names

In [8]:
# row indexes bydefault it takes

In [9]:
# pandas is used or read or perform some operation on 
# structured data

In [10]:
# data type of entire data in pandas is called dataframe

In [11]:
ls

 Volume in drive C is Windows-SSD
 Volume Serial Number is BA08-EA00

 Directory of C:\Users\91903

07-12-2023  21:38    <DIR>          .
02-04-2023  19:05    <DIR>          ..
31-07-2022  11:32    <DIR>          .astropy
31-07-2022  11:13    <DIR>          .conda
30-11-2022  14:28    <DIR>          .cufflinks
08-05-2023  16:03    <DIR>          .idea
07-12-2023  21:38    <DIR>          .ipynb_checkpoints
21-02-2022  17:38    <DIR>          .ipython
05-03-2022  10:37    <DIR>          .jupyter
31-07-2022  11:40    <DIR>          .matplotlib
03-12-2023  18:07    <DIR>          __pycache__
08-10-2022  22:23            21,198 15th jan exception handling part1.ipynb
26-02-2023  16:06             6,880 16th jan logging.ipynb
25-08-2022  18:29            56,638 18th dec practice.ipynb
18-08-2023  10:20            63,220 19th dec practice.ipynb
11-09-2023  17:09         4,672,436 2023 20dec for loop  and while ipynb.ipynb
11-09-2023  21:28            23,182 2023 21dec ipynb.ipynb
14-09-2023  20:19            30,516 2023 23dec, 8th jan function ipynb.ipynb
01-06-2023  15:09             9,891 2023 6th feb sql day2.ipynb
11-09-2023  13:41            46,294 2023 dec18th set tuple dict ipynb part2.ipynb
11-09-2023  12:26            25,571 2023 dec19th new ipynb if else.ipynb
10-09-2023  22:01            68,837 2023 dec5th str,list new ipynb.ipynb
07-05-2023  19:28           110,238 2023 modules and pycharm.ipynb
11-05-2023  16:37            11,034 2023 sql part 1 feb5th.ipynb
18-08-2023  11:24            21,293 20thdec practice.ipynb
09-04-2022  15:17            23,165 21st dec practice.ipynb
14-10-2022  16:05           100,700 22jan module discussion.ipynb
14-10-2022  17:38             5,648 22jan oops concept.ipynb
30-07-2022  13:00                 0 22jan.py
30-07-2022  13:15                29 22jan1.py
26-06-2022  21:49            22,964 23decrestart.ipynb
11-04-2022  17:05            33,103 23rd dec practice.ipynb
19-10-2022  14:31             8,048 23rd jan oops concept.ipynb
24-08-2022  17:17            34,953 29jan oops.ipynb
25-06-2022  23:46            18,529 8th jan .ipynb
16-10-2022  22:12            38,125 8th jan practice.ipynb
06-10-2022  19:59           105,942 9th jan iterator,generator and filesystem.ipynb
27-06-2022  21:47            69,372 9thjanpractice.ipynb
07-05-2023  18:05                 0 akhil.py
21-02-2022  16:16    <DIR>          anaconda3
02-12-2022  12:49             1,089 API FLASK1.ipynb
04-07-2023  11:44            14,141 Assignment 8.ipynb
04-07-2023  12:15             4,535 Assignment 9.ipynb
28-02-2022  14:55             8,732 Assignment1.ipynb
08-05-2022  18:10            15,719 assignment2.ipynb
22-08-2022  11:36            15,644 Assignment4.ipynb
14-10-2022  11:56    <DIR>          autoCompletion
16-11-2022  14:49           461,474 bank.csv
16-11-2022  14:46           461,474 bank.xls
23-09-2022  02:00             1,007 change.log
02-04-2023  19:10    <DIR>          Contacts
17-01-2022  06:13             4,843 contextMenu.xml
15-11-2022  11:25             5,845 cricket.csv
10-11-2022  11:31             1,560 datastax.ipynb
03-05-2022  12:58            55,145 dec 5th practice.ipynb
25-08-2022  11:55            41,712 dec 5th practice2.ipynb
16-08-2023  13:02            23,803 dec4th practice.ipynb
01-04-2022  17:58    <DIR>          Documents
07-12-2023  21:32    <DIR>          Downloads
24-04-2023  13:09                22 enapple.ini
13-10-2022  14:04            94,633 exception part2 and logging.ipynb
30-06-2022  21:18            35,344 excpthndlng2.ipynb
28-06-2022  23:07            12,467 exhndlng1.ipynb
02-04-2023  19:10    <DIR>          Favorites
05-10-2022  18:07            89,207 function dec 23rd class practice.ipynb
14-10-2022  11:56    <DIR>          functionList
14-10-2022  12:37               131 funmod1.py
14-10-2022  12:22                 0 funmod2.py
14-10-2022  12:53                94 funmod3.py
14-10-2022  13:00                40 funmod4.py
29-11-2022  22:57         3,078,946 graph 1.ipynb
30-11-2022  17:59         1,789,919 graph2.ipynb
01-12-2023  15:52            56,367 htd 8th jan.ipynb
28-11-2023  15:16                72 hyd 1.ipynb
02-12-2023  18:51            21,791 hyd 15th jan.ipynb
03-12-2023  14:53            51,859 hyd 16th jan.ipynb
30-11-2023  11:30            33,145 hyd 20th dec.ipynb
30-11-2023  20:07            18,848 hyd 21st dec.ipynb
01-12-2023  15:50            28,293 hyd 23rd dec.ipynb
02-12-2023  14:24           140,622 hyd 9th jan.ipynb
29-11-2023  11:37            80,734 hyd dec18th.ipynb
07-12-2023  21:38             3,341 hyd feb 26th pandas.ipynb
03-12-2023  18:14            29,972 hyd jan22nd.ipynb
02-12-2023  15:15           122,373 hyd practice book.ipynb
29-11-2023  14:02            44,090 hyd19th dec.ipynb
03-12-2023  18:13                 0 hydmodule1.py
02-12-2023  13:48               725 hydpara.txt
03-12-2023  14:47             1,074 hydtest.log
02-12-2023  18:18                19 hydtest.txt
02-12-2023  11:59                38 hydtest1.txt
03-12-2023  14:17               567 hydtest2.log
03-12-2023  14:42                 0 hydtest3.log
31-07-2022  12:59            41,601 jan22practice.ipynb
08-11-2022  15:10            12,288 joindb.db
08-11-2022  15:20             8,720 joindb.db-journal
15-11-2022  14:27            35,186 json_res.csv
28-05-2022  07:17           350,341 langs.model.xml
15-08-2021  05:50            35,500 LICENSE
06-10-2022  19:56               147 life.txt
02-04-2023  19:10    <DIR>          Links
14-10-2022  11:56    <DIR>          localization
06-10-2022  19:27             1,934 mahesh.txt
06-10-2022  18:50                51 manasa.txt
13-10-2022  13:52                 0 meethu.log
07-05-2023  18:20               180 mini.py
07-05-2023  17:55                 0 mod1.py
07-05-2023  18:12               130 mod2.py
07-05-2023  17:54                 0 module.py
14-10-2022  11:39                 0 module2.py
27-10-2022  12:23             5,444 mongodb.ipynb
02-04-2023  19:10    <DIR>          Music
30-07-2022  14:06               213 my_module.py
25-10-2022  14:40            10,208 mysql class1.ipynb
15-11-2022  11:15            78,961 NBA.csv
03-12-2023  17:57    <DIR>          notepadplus
05-12-2021  09:58                 0 nppLogNulContentCorruptionIssue.xml
25-09-2022  23:30           232,984 NppShell_06.dll
23-11-2022  17:51            50,763 numpy.ipynb
02-04-2023  19:08    <DIR>          OneDrive
31-07-2022  19:10             5,529 oops basic 22jan.ipynb
01-08-2022  15:53            11,638 oops jan23.ipynb
22-11-2022  21:35           107,440 pandas and numpy.ipynb
10-11-2022  23:34           128,025 pandas1.ipynb
15-11-2022  14:41           619,109 pandas2.ipynb
16-11-2022  15:55           141,613 pandas3.ipynb
17-11-2022  13:14               588 pandas4.ipynb
21-11-2022  19:35           173,487 pandasday4.ipynb
08-11-2022  14:51             8,192 person.db
14-10-2022  11:56    <DIR>          plugins
02-12-2022  11:38    <DIR>          Postman
03-12-2023  10:34                16 priya.txt
07-05-2023  19:11    <DIR>          PycharmProjects
29-09-2022  08:46            10,630 python assignment 5.ipynb
08-10-2022  23:27            14,458 python basic assignment 6.ipynb
15-07-2023  12:52             7,374 python basic programming assignment 11.ipynb
20-07-2023  15:51             6,955 python basic programming assignment 12.ipynb
30-09-2022  18:26             6,317 python basic programming assignment 5.ipynb
07-10-2022  00:13             6,545 python basic programming assignment 6.ipynb
13-10-2022  16:11             4,776 python basic programming assignment 7.ipynb
23-09-2022  16:44             7,776 python basic programming assignment4.ipynb
11-07-2023  15:08             1,383 python programming assignment 10.ipynb
14-07-2023  10:20             9,645 python programming assignment 11.ipynb
04-07-2023  13:58             5,375 python programming assignment 8.ipynb
09-07-2023  17:13            10,556 python programming assignment 9.ipynb
22-08-2022  15:53             4,908 python programming assignment1.ipynb
21-09-2022  14:12             4,130 python programming assignment2.ipynb
22-09-2022  14:06            26,533 python programming assignment3.ipynb
08-11-2022  14:54             8,192 raj.db
08-10-2022  22:02                 9 raji.txt
06-10-2022  19:42                58 rama.txt
27-05-2021  04:27             1,526 readme.txt
21-06-2022  13:45            23,522 restart 20dec.ipynb
21-06-2022  17:07            21,171 restart 21dec.ipynb
17-06-2022  16:30            17,684 restart dec19.ipynb
14-10-2022  12:24                44 rfunmod1.py
13-10-2022  13:29               480 ritu.log
10-11-2022  19:13            14,905 Sales.csv
10-11-2022  19:36               201 sample.csv
10-11-2022  23:15               232 sample.xls.csv
02-04-2023  19:10    <DIR>          Saved Games
30-11-2022  14:30    <DIR>          seaborn-data
02-04-2023  19:10    <DIR>          Searches
13-10-2022  13:35               904 seethu.log
27-05-2021  04:27               965 shortcuts.xml
08-11-2022  19:47            77,976 sql lite 08112022.ipynb
25-10-2022  14:40             8,079 sql part2.ipynb
22-10-2022  23:32             7,994 sql2.ipynb
20-09-2022  22:39           174,773 stylers.model.xml
30-09-2022  17:37             6,652 sudhasirqsadans.ipynb
30-06-2022  22:41               310 test.log
02-12-2023  11:55                 0 test.txt
13-10-2022  12:17                 4 test1
13-10-2022  11:53                22 test1.txt
30-07-2022  13:47               225 test11.py
30-06-2022  22:53               278 test2.log
27-06-2022  13:24                31 test2.txt
14-10-2022  11:29                 0 test3.py
28-06-2022  23:08                11 test3.txt
30-06-2022  16:50                 0 test43.txt
27-06-2022  21:30               551 test5.txt
07-05-2023  18:31               138 testu.py
14-10-2022  11:56    <DIR>          themes
28-02-2022  20:21            53,575 Untitled.ipynb
01-03-2022  14:37                72 Untitled1.ipynb
27-02-2023  14:30             1,679 Untitled10.ipynb
09-05-2023  10:29                72 Untitled11.ipynb
04-07-2023  13:54             8,651 Untitled12.ipynb
03-08-2023  10:33             3,443 Untitled13.ipynb
07-12-2023  21:37                72 Untitled14.ipynb
03-03-2022  15:56            36,553 Untitled2.ipynb
21-06-2022  15:32               588 Untitled3.ipynb
27-06-2022  22:55             5,082 Untitled4.ipynb
29-06-2022  00:49             5,617 Untitled5.ipynb
30-07-2022  12:48             1,518 Untitled6.ipynb
24-08-2022  17:18            18,874 Untitled7.ipynb
16-10-2022  10:53               588 Untitled8.ipynb
28-11-2022  14:32               796 Untitled9.ipynb
14-10-2022  11:56    <DIR>          updater
02-04-2023  19:10    <DIR>          Videos
             167 File(s)     15,171,028 bytes
              32 Dir(s)  416,426,782,720 bytes free

In [12]:
pd.read_csv("Details.csv")

   S.no    Name  Age  Designation         Place  Salary
0     1   Pavan   35      Husband       Chirala   30000
1     2    Raji   35         Wife  Narasaraopet   20000
2     3   Sanvi    6     Daughter       Chirala   50000
3     4   Seivi    6     Daughter       Chirala   50000
4     5    Rama   55       Mother  Narasaraopet   12000
5     6  Ramana   85      Gmother  Narasaraopet   15000
6     7  Manasa   30       Sister  Narasaraopet   30000
7     8   Ramya   30    Lawsister     Hyderabad   20000
8     9  Himani    6  Lawdaughter     Hyderabad   50000
9    10   Tinku   28    Lawsister     Hyderabad   30000

In [15]:
pd.read_csv('C:\Users\91903\day.csv')

SyntaxError: (unicode error) 'unicodeescape' codec can't decode bytes in position 2-3: truncated \UXXXXXXXX escape (Temp/ipykernel_45832/3105383855.py, line 1)

In [16]:
# if u get unicode error , place r infront of c:\

In [17]:
pd.read_csv(r'C:\Users\91903\day.csv')

    Numeric  Numeric-2 Numeric-Suffix
0         1          1            1st
1         2          2            2nd
2         3          3            3rd
3         4          4            4th
4         5          5            5th
5         6          6            6th
6         7          7            7th
7         8          8            8th
8         9          9            9th
9        10         10           10th
10       11         11           11th
11       12         12           12th
12       13         13           13th
13       14         14           14th
14       15         15           15th
15       16         16           16th
16       17         17           17th
17       18         18           18th
18       19         19           19th
19       20         20           20th
20       21         21           21st
21       22         22           22nd
22       23         23           23rd
23       24         24           24th
24       25         25           25th
25       26         26           26th
26       27         27           27th
27       28         28           28th
28       29         29           29th
29       30         30           30th
30       31         31           31st

In [18]:
df=pd.read_csv(r'C:\Users\91903\day.csv')

In [19]:
df

    Numeric  Numeric-2 Numeric-Suffix
0         1          1            1st
1         2          2            2nd
2         3          3            3rd
3         4          4            4th
4         5          5            5th
5         6          6            6th
6         7          7            7th
7         8          8            8th
8         9          9            9th
9        10         10           10th
10       11         11           11th
11       12         12           12th
12       13         13           13th
13       14         14           14th
14       15         15           15th
15       16         16           16th
16       17         17           17th
17       18         18           18th
18       19         19           19th
19       20         20           20th
20       21         21           21st
21       22         22           22nd
22       23         23           23rd
23       24         24           24th
24       25         25           25th
25       26         26           26th
26       27         27           27th
27       28         28           28th
28       29         29           29th
29       30         30           30th
30       31         31           31st

In [20]:
a=1

In [21]:
type(a)

int

In [22]:
type(df)

pandas.core.frame.DataFrame

In [23]:
ls

 Volume in drive C is Windows-SSD
 Volume Serial Number is BA08-EA00

 Directory of C:\Users\91903

07-12-2023  21:56    <DIR>          .
02-04-2023  19:05    <DIR>          ..
31-07-2022  11:32    <DIR>          .astropy
31-07-2022  11:13    <DIR>          .conda
30-11-2022  14:28    <DIR>          .cufflinks
08-05-2023  16:03    <DIR>          .idea
07-12-2023  21:38    <DIR>          .ipynb_checkpoints
21-02-2022  17:38    <DIR>          .ipython
05-03-2022  10:37    <DIR>          .jupyter
31-07-2022  11:40    <DIR>          .matplotlib
03-12-2023  18:07    <DIR>          __pycache__
08-10-2022  22:23            21,198 15th jan exception handling part1.ipynb
26-02-2023  16:06             6,880 16th jan logging.ipynb
25-08-2022  18:29            56,638 18th dec practice.ipynb
18-08-2023  10:20            63,220 19th dec practice.ipynb
11-09-2023  17:09         4,672,436 2023 20dec for loop  and while ipynb.ipynb
11-09-2023  21:28            23,182 2023 21dec ipynb.ipynb
14-09-2023  20:19            30,516 2023 23dec, 8th jan function ipynb.ipynb
01-06-2023  15:09             9,891 2023 6th feb sql day2.ipynb
11-09-2023  13:41            46,294 2023 dec18th set tuple dict ipynb part2.ipynb
11-09-2023  12:26            25,571 2023 dec19th new ipynb if else.ipynb
10-09-2023  22:01            68,837 2023 dec5th str,list new ipynb.ipynb
07-05-2023  19:28           110,238 2023 modules and pycharm.ipynb
11-05-2023  16:37            11,034 2023 sql part 1 feb5th.ipynb
18-08-2023  11:24            21,293 20thdec practice.ipynb
09-04-2022  15:17            23,165 21st dec practice.ipynb
14-10-2022  16:05           100,700 22jan module discussion.ipynb
14-10-2022  17:38             5,648 22jan oops concept.ipynb
30-07-2022  13:00                 0 22jan.py
30-07-2022  13:15                29 22jan1.py
26-06-2022  21:49            22,964 23decrestart.ipynb
11-04-2022  17:05            33,103 23rd dec practice.ipynb
19-10-2022  14:31             8,048 23rd jan oops concept.ipynb
24-08-2022  17:17            34,953 29jan oops.ipynb
25-06-2022  23:46            18,529 8th jan .ipynb
16-10-2022  22:12            38,125 8th jan practice.ipynb
06-10-2022  19:59           105,942 9th jan iterator,generator and filesystem.ipynb
27-06-2022  21:47            69,372 9thjanpractice.ipynb
07-05-2023  18:05                 0 akhil.py
21-02-2022  16:16    <DIR>          anaconda3
02-12-2022  12:49             1,089 API FLASK1.ipynb
04-07-2023  11:44            14,141 Assignment 8.ipynb
04-07-2023  12:15             4,535 Assignment 9.ipynb
28-02-2022  14:55             8,732 Assignment1.ipynb
08-05-2022  18:10            15,719 assignment2.ipynb
22-08-2022  11:36            15,644 Assignment4.ipynb
14-10-2022  11:56    <DIR>          autoCompletion
16-11-2022  14:49           461,474 bank.csv
16-11-2022  14:46           461,474 bank.xls
23-09-2022  02:00             1,007 change.log
02-04-2023  19:10    <DIR>          Contacts
17-01-2022  06:13             4,843 contextMenu.xml
15-11-2022  11:25             5,845 cricket.csv
10-11-2022  11:31             1,560 datastax.ipynb
07-12-2023  21:49               355 day.csv
03-05-2022  12:58            55,145 dec 5th practice.ipynb
25-08-2022  11:55            41,712 dec 5th practice2.ipynb
16-08-2023  13:02            23,803 dec4th practice.ipynb
07-12-2023  21:45               410 Details.csv
01-04-2022  17:58    <DIR>          Documents
07-12-2023  21:50    <DIR>          Downloads
24-04-2023  13:09                22 enapple.ini
13-10-2022  14:04            94,633 exception part2 and logging.ipynb
30-06-2022  21:18            35,344 excpthndlng2.ipynb
28-06-2022  23:07            12,467 exhndlng1.ipynb
02-04-2023  19:10    <DIR>          Favorites
05-10-2022  18:07            89,207 function dec 23rd class practice.ipynb
14-10-2022  11:56    <DIR>          functionList
14-10-2022  12:37               131 funmod1.py
14-10-2022  12:22                 0 funmod2.py
14-10-2022  12:53                94 funmod3.py
14-10-2022  13:00                40 funmod4.py
29-11-2022  22:57         3,078,946 graph 1.ipynb
30-11-2022  17:59         1,789,919 graph2.ipynb
01-12-2023  15:52            56,367 htd 8th jan.ipynb
28-11-2023  15:16                72 hyd 1.ipynb
02-12-2023  18:51            21,791 hyd 15th jan.ipynb
03-12-2023  14:53            51,859 hyd 16th jan.ipynb
30-11-2023  11:30            33,145 hyd 20th dec.ipynb
30-11-2023  20:07            18,848 hyd 21st dec.ipynb
01-12-2023  15:50            28,293 hyd 23rd dec.ipynb
02-12-2023  14:24           140,622 hyd 9th jan.ipynb
29-11-2023  11:37            80,734 hyd dec18th.ipynb
07-12-2023  21:56            38,179 hyd feb 26th pandas.ipynb
03-12-2023  18:14            29,972 hyd jan22nd.ipynb
02-12-2023  15:15           122,373 hyd practice book.ipynb
29-11-2023  14:02            44,090 hyd19th dec.ipynb
03-12-2023  18:13                 0 hydmodule1.py
02-12-2023  13:48               725 hydpara.txt
03-12-2023  14:47             1,074 hydtest.log
02-12-2023  18:18                19 hydtest.txt
02-12-2023  11:59                38 hydtest1.txt
03-12-2023  14:17               567 hydtest2.log
03-12-2023  14:42                 0 hydtest3.log
31-07-2022  12:59            41,601 jan22practice.ipynb
08-11-2022  15:10            12,288 joindb.db
08-11-2022  15:20             8,720 joindb.db-journal
15-11-2022  14:27            35,186 json_res.csv
28-05-2022  07:17           350,341 langs.model.xml
15-08-2021  05:50            35,500 LICENSE
06-10-2022  19:56               147 life.txt
02-04-2023  19:10    <DIR>          Links
14-10-2022  11:56    <DIR>          localization
06-10-2022  19:27             1,934 mahesh.txt
06-10-2022  18:50                51 manasa.txt
13-10-2022  13:52                 0 meethu.log
07-05-2023  18:20               180 mini.py
07-05-2023  17:55                 0 mod1.py
07-05-2023  18:12               130 mod2.py
07-05-2023  17:54                 0 module.py
14-10-2022  11:39                 0 module2.py
27-10-2022  12:23             5,444 mongodb.ipynb
02-04-2023  19:10    <DIR>          Music
30-07-2022  14:06               213 my_module.py
25-10-2022  14:40            10,208 mysql class1.ipynb
15-11-2022  11:15            78,961 NBA.csv
03-12-2023  17:57    <DIR>          notepadplus
05-12-2021  09:58                 0 nppLogNulContentCorruptionIssue.xml
25-09-2022  23:30           232,984 NppShell_06.dll
23-11-2022  17:51            50,763 numpy.ipynb
02-04-2023  19:08    <DIR>          OneDrive
31-07-2022  19:10             5,529 oops basic 22jan.ipynb
01-08-2022  15:53            11,638 oops jan23.ipynb
22-11-2022  21:35           107,440 pandas and numpy.ipynb
10-11-2022  23:34           128,025 pandas1.ipynb
15-11-2022  14:41           619,109 pandas2.ipynb
16-11-2022  15:55           141,613 pandas3.ipynb
17-11-2022  13:14               588 pandas4.ipynb
21-11-2022  19:35           173,487 pandasday4.ipynb
08-11-2022  14:51             8,192 person.db
14-10-2022  11:56    <DIR>          plugins
02-12-2022  11:38    <DIR>          Postman
03-12-2023  10:34                16 priya.txt
07-05-2023  19:11    <DIR>          PycharmProjects
29-09-2022  08:46            10,630 python assignment 5.ipynb
08-10-2022  23:27            14,458 python basic assignment 6.ipynb
15-07-2023  12:52             7,374 python basic programming assignment 11.ipynb
20-07-2023  15:51             6,955 python basic programming assignment 12.ipynb
30-09-2022  18:26             6,317 python basic programming assignment 5.ipynb
07-10-2022  00:13             6,545 python basic programming assignment 6.ipynb
13-10-2022  16:11             4,776 python basic programming assignment 7.ipynb
23-09-2022  16:44             7,776 python basic programming assignment4.ipynb
11-07-2023  15:08             1,383 python programming assignment 10.ipynb
14-07-2023  10:20             9,645 python programming assignment 11.ipynb
04-07-2023  13:58             5,375 python programming assignment 8.ipynb
09-07-2023  17:13            10,556 python programming assignment 9.ipynb
22-08-2022  15:53             4,908 python programming assignment1.ipynb
21-09-2022  14:12             4,130 python programming assignment2.ipynb
22-09-2022  14:06            26,533 python programming assignment3.ipynb
08-11-2022  14:54             8,192 raj.db
08-10-2022  22:02                 9 raji.txt
06-10-2022  19:42                58 rama.txt
27-05-2021  04:27             1,526 readme.txt
21-06-2022  13:45            23,522 restart 20dec.ipynb
21-06-2022  17:07            21,171 restart 21dec.ipynb
17-06-2022  16:30            17,684 restart dec19.ipynb
14-10-2022  12:24                44 rfunmod1.py
13-10-2022  13:29               480 ritu.log
10-11-2022  19:13            14,905 Sales.csv
10-11-2022  19:36               201 sample.csv
10-11-2022  23:15               232 sample.xls.csv
02-04-2023  19:10    <DIR>          Saved Games
30-11-2022  14:30    <DIR>          seaborn-data
02-04-2023  19:10    <DIR>          Searches
13-10-2022  13:35               904 seethu.log
27-05-2021  04:27               965 shortcuts.xml
08-11-2022  19:47            77,976 sql lite 08112022.ipynb
25-10-2022  14:40             8,079 sql part2.ipynb
22-10-2022  23:32             7,994 sql2.ipynb
20-09-2022  22:39           174,773 stylers.model.xml
30-09-2022  17:37             6,652 sudhasirqsadans.ipynb
30-06-2022  22:41               310 test.log
02-12-2023  11:55                 0 test.txt
13-10-2022  12:17                 4 test1
13-10-2022  11:53                22 test1.txt
30-07-2022  13:47               225 test11.py
30-06-2022  22:53               278 test2.log
27-06-2022  13:24                31 test2.txt
14-10-2022  11:29                 0 test3.py
28-06-2022  23:08                11 test3.txt
30-06-2022  16:50                 0 test43.txt
27-06-2022  21:30               551 test5.txt
07-05-2023  18:31               138 testu.py
14-10-2022  11:56    <DIR>          themes
28-02-2022  20:21            53,575 Untitled.ipynb
01-03-2022  14:37                72 Untitled1.ipynb
27-02-2023  14:30             1,679 Untitled10.ipynb
09-05-2023  10:29                72 Untitled11.ipynb
04-07-2023  13:54             8,651 Untitled12.ipynb
03-08-2023  10:33             3,443 Untitled13.ipynb
07-12-2023  21:37                72 Untitled14.ipynb
03-03-2022  15:56            36,553 Untitled2.ipynb
21-06-2022  15:32               588 Untitled3.ipynb
27-06-2022  22:55             5,082 Untitled4.ipynb
29-06-2022  00:49             5,617 Untitled5.ipynb
30-07-2022  12:48             1,518 Untitled6.ipynb
24-08-2022  17:18            18,874 Untitled7.ipynb
16-10-2022  10:53               588 Untitled8.ipynb
28-11-2022  14:32               796 Untitled9.ipynb
14-10-2022  11:56    <DIR>          updater
02-04-2023  19:10    <DIR>          Videos
             169 File(s)     15,206,631 bytes
              32 Dir(s)  416,404,185,088 bytes free

In [24]:
df=pd.read_csv("Details.csv")

In [25]:
df

   S.no    Name  Age  Designation         Place  Salary
0     1   Pavan   35      Husband       Chirala   30000
1     2    Raji   35         Wife  Narasaraopet   20000
2     3   Sanvi    6     Daughter       Chirala   50000
3     4   Seivi    6     Daughter       Chirala   50000
4     5    Rama   55       Mother  Narasaraopet   12000
5     6  Ramana   85      Gmother  Narasaraopet   15000
6     7  Manasa   30       Sister  Narasaraopet   30000
7     8   Ramya   30    Lawsister     Hyderabad   20000
8     9  Himani    6  Lawdaughter     Hyderabad   50000
9    10   Tinku   28    Lawsister     Hyderabad   30000

In [27]:
pd.read_csv("Details.csv",header=None)
# this removes header means column names

       0       1    2            3             4       5
0   S.no    Name  Age  Designation         Place  Salary
1      1   Pavan   35      Husband       Chirala   30000
2      2    Raji   35         Wife  Narasaraopet   20000
3      3   Sanvi    6     Daughter       Chirala   50000
4      4   Seivi    6     Daughter       Chirala   50000
5      5    Rama   55       Mother  Narasaraopet   12000
6      6  Ramana   85      Gmother  Narasaraopet   15000
7      7  Manasa   30       Sister  Narasaraopet   30000
8      8   Ramya   30    Lawsister     Hyderabad   20000
9      9  Himani    6  Lawdaughter     Hyderabad   50000
10    10   Tinku   28    Lawsister     Hyderabad   30000

In [29]:
pd.read_csv("Details.csv", names=[100,200,300,400,500,600])
# this changes column names

     100     200  300          400           500     600
0   S.no    Name  Age  Designation         Place  Salary
1      1   Pavan   35      Husband       Chirala   30000
2      2    Raji   35         Wife  Narasaraopet   20000
3      3   Sanvi    6     Daughter       Chirala   50000
4      4   Seivi    6     Daughter       Chirala   50000
5      5    Rama   55       Mother  Narasaraopet   12000
6      6  Ramana   85      Gmother  Narasaraopet   15000
7      7  Manasa   30       Sister  Narasaraopet   30000
8      8   Ramya   30    Lawsister     Hyderabad   20000
9      9  Himani    6  Lawdaughter     Hyderabad   50000
10    10   Tinku   28    Lawsister     Hyderabad   30000

In [30]:
pd.read_csv("Details.csv")

   S.no    Name  Age  Designation         Place  Salary
0     1   Pavan   35      Husband       Chirala   30000
1     2    Raji   35         Wife  Narasaraopet   20000
2     3   Sanvi    6     Daughter       Chirala   50000
3     4   Seivi    6     Daughter       Chirala   50000
4     5    Rama   55       Mother  Narasaraopet   12000
5     6  Ramana   85      Gmother  Narasaraopet   15000
6     7  Manasa   30       Sister  Narasaraopet   30000
7     8   Ramya   30    Lawsister     Hyderabad   20000
8     9  Himani    6  Lawdaughter     Hyderabad   50000
9    10   Tinku   28    Lawsister     Hyderabad   30000

In [31]:
pd.read_csv("Details.csv")

   S.no    Name  Age  Designation         Place  Salary             Email
0     1   Pavan   35      Husband       Chirala   30000   pavan@gmail.com
1     2    Raji   35         Wife  Narasaraopet   20000    raji@gmail.com
2     3   Sanvi    6     Daughter       Chirala   50000   sanvi@gmail.com
3     4   Seivi    6     Daughter       Chirala   50000   seivi@gmail.com
4     5    Rama   55       Mother  Narasaraopet   12000    rama@gmail.com
5     6  Ramana   85      Gmother  Narasaraopet   15000  ramana@gmail.com
6     7  Manasa   30       Sister  Narasaraopet   30000  manasa@gmail.com
7     8   Ramya   30    Lawsister     Hyderabad   20000   ramya@gmail.com
8     9  Himani    6  Lawdaughter     Hyderabad   50000  himani@gmail.com
9    10   Tinku   28    Lawsister     Hyderabad   30000   tinku@gmail.com

In [33]:
pd.read_csv("Details.csv",sep='@')

                                              S.no,Name,Age,Designation,Place,Salary,Email
1,Pavan,35,Husband,Chirala,30000,pavan                                           gmail.com
2,Raji,35,Wife,Narasaraopet,20000,raji                                           gmail.com
3,Sanvi,6,Daughter,Chirala,50000,sanvi                                           gmail.com
4,Seivi,6,Daughter,Chirala,50000,seivi                                           gmail.com
5,Rama,55,Mother,Narasaraopet,12000,rama                                         gmail.com
6,Ramana,85,Gmother,Narasaraopet,15000,ramana                                    gmail.com
7,Manasa,30,Sister,Narasaraopet,30000,manasa                                     gmail.com
8,Ramya,30,Lawsister,Hyderabad,20000,ramya                                       gmail.com
9,Himani,6,Lawdaughter,Hyderabad,50000,himani                                    gmail.com
10,Tinku,28,Lawsister,Hyderabad,30000,tinku                                      gmail.com

In [42]:
df=pd.read_csv("Details.csv",sep=',')

In [43]:
df

   S.no    Name  Age  Designation         Place  Salary             Email
0     1   Pavan   35      Husband       Chirala   30000   pavan@gmail.com
1     2    Raji   35         Wife  Narasaraopet   20000    raji@gmail.com
2     3   Sanvi    6     Daughter       Chirala   50000   sanvi@gmail.com
3     4   Seivi    6     Daughter       Chirala   50000   seivi@gmail.com
4     5    Rama   55       Mother  Narasaraopet   12000    rama@gmail.com
5     6  Ramana   85      Gmother  Narasaraopet   15000  ramana@gmail.com
6     7  Manasa   30       Sister  Narasaraopet   30000  manasa@gmail.com
7     8   Ramya   30    Lawsister     Hyderabad   20000   ramya@gmail.com
8     9  Himani    6  Lawdaughter     Hyderabad   50000  himani@gmail.com
9    10   Tinku   28    Lawsister     Hyderabad   30000   tinku@gmail.com

   S.no    Name  Age  Designation         Place  Salary             Email
0     1   Pavan   35      Husband       Chirala   30000   pavan@gmail.com
1     2    Raji   35         Wife  Narasaraopet   20000    raji@gmail.com
2     3   Sanvi    6     Daughter       Chirala   50000   sanvi@gmail.com
3     4   Seivi    6     Daughter       Chirala   50000   seivi@gmail.com
4     5    Rama   55       Mother  Narasaraopet   12000    rama@gmail.com
5     6  Ramana   85      Gmother  Narasaraopet   15000  ramana@gmail.com
6     7  Manasa   30       Sister  Narasaraopet   30000  manasa@gmail.com
7     8   Ramya   30    Lawsister     Hyderabad   20000   ramya@gmail.com
8     9  Himani    6  Lawdaughter     Hyderabad   50000  himani@gmail.com
9    10   Tinku   28    Lawsister     Hyderabad   30000   tinku@gmail.com

In [48]:
pd.read_csv("Details.csv",skiprows=[1,2,5])
#skips the rows

   S.no    Name  Age  Designation         Place  Salary             Email
0     3   Sanvi    6     Daughter       Chirala   50000   sanvi@gmail.com
1     4   Seivi    6     Daughter       Chirala   50000   seivi@gmail.com
2     6  Ramana   85      Gmother  Narasaraopet   15000  ramana@gmail.com
3     7  Manasa   30       Sister  Narasaraopet   30000  manasa@gmail.com
4     8   Ramya   30    Lawsister     Hyderabad   20000   ramya@gmail.com
5     9  Himani    6  Lawdaughter     Hyderabad   50000  himani@gmail.com
6    10   Tinku   28    Lawsister     Hyderabad   30000   tinku@gmail.com

In [51]:
df=pd.read_csv("Details.csv",skiprows=[1,2,5])

In [52]:
df

   S.no    Name  Age  Designation         Place  Salary             Email
0     3   Sanvi    6     Daughter       Chirala   50000   sanvi@gmail.com
1     4   Seivi    6     Daughter       Chirala   50000   seivi@gmail.com
2     6  Ramana   85      Gmother  Narasaraopet   15000  ramana@gmail.com
3     7  Manasa   30       Sister  Narasaraopet   30000  manasa@gmail.com
4     8   Ramya   30    Lawsister     Hyderabad   20000   ramya@gmail.com
5     9  Himani    6  Lawdaughter     Hyderabad   50000  himani@gmail.com
6    10   Tinku   28    Lawsister     Hyderabad   30000   tinku@gmail.com

In [53]:
type(df)

pandas.core.frame.DataFrame

In [54]:
ls

 Volume in drive C is Windows-SSD
 Volume Serial Number is BA08-EA00

 Directory of C:\Users\91903

07-12-2023  22:36    <DIR>          .
02-04-2023  19:05    <DIR>          ..
31-07-2022  11:32    <DIR>          .astropy
31-07-2022  11:13    <DIR>          .conda
30-11-2022  14:28    <DIR>          .cufflinks
08-05-2023  16:03    <DIR>          .idea
07-12-2023  21:38    <DIR>          .ipynb_checkpoints
21-02-2022  17:38    <DIR>          .ipython
05-03-2022  10:37    <DIR>          .jupyter
31-07-2022  11:40    <DIR>          .matplotlib
03-12-2023  18:07    <DIR>          __pycache__
08-10-2022  22:23            21,198 15th jan exception handling part1.ipynb
26-02-2023  16:06             6,880 16th jan logging.ipynb
25-08-2022  18:29            56,638 18th dec practice.ipynb
18-08-2023  10:20            63,220 19th dec practice.ipynb
11-09-2023  17:09         4,672,436 2023 20dec for loop  and while ipynb.ipynb
11-09-2023  21:28            23,182 2023 21dec ipynb.ipynb
14-09-2023  20:19            30,516 2023 23dec, 8th jan function ipynb.ipynb
01-06-2023  15:09             9,891 2023 6th feb sql day2.ipynb
11-09-2023  13:41            46,294 2023 dec18th set tuple dict ipynb part2.ipynb
11-09-2023  12:26            25,571 2023 dec19th new ipynb if else.ipynb
10-09-2023  22:01            68,837 2023 dec5th str,list new ipynb.ipynb
07-05-2023  19:28           110,238 2023 modules and pycharm.ipynb
11-05-2023  16:37            11,034 2023 sql part 1 feb5th.ipynb
18-08-2023  11:24            21,293 20thdec practice.ipynb
09-04-2022  15:17            23,165 21st dec practice.ipynb
14-10-2022  16:05           100,700 22jan module discussion.ipynb
14-10-2022  17:38             5,648 22jan oops concept.ipynb
30-07-2022  13:00                 0 22jan.py
30-07-2022  13:15                29 22jan1.py
26-06-2022  21:49            22,964 23decrestart.ipynb
11-04-2022  17:05            33,103 23rd dec practice.ipynb
19-10-2022  14:31             8,048 23rd jan oops concept.ipynb
24-08-2022  17:17            34,953 29jan oops.ipynb
25-06-2022  23:46            18,529 8th jan .ipynb
16-10-2022  22:12            38,125 8th jan practice.ipynb
06-10-2022  19:59           105,942 9th jan iterator,generator and filesystem.ipynb
27-06-2022  21:47            69,372 9thjanpractice.ipynb
07-05-2023  18:05                 0 akhil.py
21-02-2022  16:16    <DIR>          anaconda3
02-12-2022  12:49             1,089 API FLASK1.ipynb
04-07-2023  11:44            14,141 Assignment 8.ipynb
04-07-2023  12:15             4,535 Assignment 9.ipynb
28-02-2022  14:55             8,732 Assignment1.ipynb
08-05-2022  18:10            15,719 assignment2.ipynb
22-08-2022  11:36            15,644 Assignment4.ipynb
14-10-2022  11:56    <DIR>          autoCompletion
16-11-2022  14:49           461,474 bank.csv
16-11-2022  14:46           461,474 bank.xls
23-09-2022  02:00             1,007 change.log
02-04-2023  19:10    <DIR>          Contacts
17-01-2022  06:13             4,843 contextMenu.xml
15-11-2022  11:25             5,845 cricket.csv
10-11-2022  11:31             1,560 datastax.ipynb
07-12-2023  21:49               355 day.csv
03-05-2022  12:58            55,145 dec 5th practice.ipynb
25-08-2022  11:55            41,712 dec 5th practice2.ipynb
16-08-2023  13:02            23,803 dec4th practice.ipynb
07-12-2023  22:30               577 Details.csv
01-04-2022  17:58    <DIR>          Documents
07-12-2023  21:50    <DIR>          Downloads
24-04-2023  13:09                22 enapple.ini
13-10-2022  14:04            94,633 exception part2 and logging.ipynb
30-06-2022  21:18            35,344 excpthndlng2.ipynb
28-06-2022  23:07            12,467 exhndlng1.ipynb
02-04-2023  19:10    <DIR>          Favorites
05-10-2022  18:07            89,207 function dec 23rd class practice.ipynb
14-10-2022  11:56    <DIR>          functionList
14-10-2022  12:37               131 funmod1.py
14-10-2022  12:22                 0 funmod2.py
14-10-2022  12:53                94 funmod3.py
14-10-2022  13:00                40 funmod4.py
29-11-2022  22:57         3,078,946 graph 1.ipynb
30-11-2022  17:59         1,789,919 graph2.ipynb
01-12-2023  15:52            56,367 htd 8th jan.ipynb
28-11-2023  15:16                72 hyd 1.ipynb
02-12-2023  18:51            21,791 hyd 15th jan.ipynb
03-12-2023  14:53            51,859 hyd 16th jan.ipynb
30-11-2023  11:30            33,145 hyd 20th dec.ipynb
30-11-2023  20:07            18,848 hyd 21st dec.ipynb
01-12-2023  15:50            28,293 hyd 23rd dec.ipynb
02-12-2023  14:24           140,622 hyd 9th jan.ipynb
29-11-2023  11:37            80,734 hyd dec18th.ipynb
07-12-2023  22:36            96,394 hyd feb 26th pandas.ipynb
03-12-2023  18:14            29,972 hyd jan22nd.ipynb
02-12-2023  15:15           122,373 hyd practice book.ipynb
29-11-2023  14:02            44,090 hyd19th dec.ipynb
03-12-2023  18:13                 0 hydmodule1.py
02-12-2023  13:48               725 hydpara.txt
03-12-2023  14:47             1,074 hydtest.log
02-12-2023  18:18                19 hydtest.txt
02-12-2023  11:59                38 hydtest1.txt
03-12-2023  14:17               567 hydtest2.log
03-12-2023  14:42                 0 hydtest3.log
31-07-2022  12:59            41,601 jan22practice.ipynb
08-11-2022  15:10            12,288 joindb.db
08-11-2022  15:20             8,720 joindb.db-journal
15-11-2022  14:27            35,186 json_res.csv
28-05-2022  07:17           350,341 langs.model.xml
15-08-2021  05:50            35,500 LICENSE
06-10-2022  19:56               147 life.txt
02-04-2023  19:10    <DIR>          Links
14-10-2022  11:56    <DIR>          localization
06-10-2022  19:27             1,934 mahesh.txt
06-10-2022  18:50                51 manasa.txt
13-10-2022  13:52                 0 meethu.log
07-05-2023  18:20               180 mini.py
07-05-2023  17:55                 0 mod1.py
07-05-2023  18:12               130 mod2.py
07-05-2023  17:54                 0 module.py
14-10-2022  11:39                 0 module2.py
27-10-2022  12:23             5,444 mongodb.ipynb
02-04-2023  19:10    <DIR>          Music
30-07-2022  14:06               213 my_module.py
25-10-2022  14:40            10,208 mysql class1.ipynb
15-11-2022  11:15            78,961 NBA.csv
03-12-2023  17:57    <DIR>          notepadplus
05-12-2021  09:58                 0 nppLogNulContentCorruptionIssue.xml
25-09-2022  23:30           232,984 NppShell_06.dll
23-11-2022  17:51            50,763 numpy.ipynb
02-04-2023  19:08    <DIR>          OneDrive
31-07-2022  19:10             5,529 oops basic 22jan.ipynb
01-08-2022  15:53            11,638 oops jan23.ipynb
22-11-2022  21:35           107,440 pandas and numpy.ipynb
10-11-2022  23:34           128,025 pandas1.ipynb
15-11-2022  14:41           619,109 pandas2.ipynb
16-11-2022  15:55           141,613 pandas3.ipynb
17-11-2022  13:14               588 pandas4.ipynb
21-11-2022  19:35           173,487 pandasday4.ipynb
08-11-2022  14:51             8,192 person.db
14-10-2022  11:56    <DIR>          plugins
02-12-2022  11:38    <DIR>          Postman
03-12-2023  10:34                16 priya.txt
07-05-2023  19:11    <DIR>          PycharmProjects
29-09-2022  08:46            10,630 python assignment 5.ipynb
08-10-2022  23:27            14,458 python basic assignment 6.ipynb
15-07-2023  12:52             7,374 python basic programming assignment 11.ipynb
20-07-2023  15:51             6,955 python basic programming assignment 12.ipynb
30-09-2022  18:26             6,317 python basic programming assignment 5.ipynb
07-10-2022  00:13             6,545 python basic programming assignment 6.ipynb
13-10-2022  16:11             4,776 python basic programming assignment 7.ipynb
23-09-2022  16:44             7,776 python basic programming assignment4.ipynb
11-07-2023  15:08             1,383 python programming assignment 10.ipynb
14-07-2023  10:20             9,645 python programming assignment 11.ipynb
04-07-2023  13:58             5,375 python programming assignment 8.ipynb
09-07-2023  17:13            10,556 python programming assignment 9.ipynb
22-08-2022  15:53             4,908 python programming assignment1.ipynb
21-09-2022  14:12             4,130 python programming assignment2.ipynb
22-09-2022  14:06            26,533 python programming assignment3.ipynb
08-11-2022  14:54             8,192 raj.db
08-10-2022  22:02                 9 raji.txt
06-10-2022  19:42                58 rama.txt
27-05-2021  04:27             1,526 readme.txt
21-06-2022  13:45            23,522 restart 20dec.ipynb
21-06-2022  17:07            21,171 restart 21dec.ipynb
17-06-2022  16:30            17,684 restart dec19.ipynb
14-10-2022  12:24                44 rfunmod1.py
13-10-2022  13:29               480 ritu.log
10-11-2022  19:13            14,905 Sales.csv
10-11-2022  19:36               201 sample.csv
10-11-2022  23:15               232 sample.xls.csv
02-04-2023  19:10    <DIR>          Saved Games
30-11-2022  14:30    <DIR>          seaborn-data
02-04-2023  19:10    <DIR>          Searches
13-10-2022  13:35               904 seethu.log
27-05-2021  04:27               965 shortcuts.xml
08-11-2022  19:47            77,976 sql lite 08112022.ipynb
25-10-2022  14:40             8,079 sql part2.ipynb
22-10-2022  23:32             7,994 sql2.ipynb
20-09-2022  22:39           174,773 stylers.model.xml
30-09-2022  17:37             6,652 sudhasirqsadans.ipynb
30-06-2022  22:41               310 test.log
02-12-2023  11:55                 0 test.txt
13-10-2022  12:17                 4 test1
13-10-2022  11:53                22 test1.txt
30-07-2022  13:47               225 test11.py
30-06-2022  22:53               278 test2.log
27-06-2022  13:24                31 test2.txt
14-10-2022  11:29                 0 test3.py
28-06-2022  23:08                11 test3.txt
30-06-2022  16:50                 0 test43.txt
27-06-2022  21:30               551 test5.txt
07-05-2023  18:31               138 testu.py
14-10-2022  11:56    <DIR>          themes
28-02-2022  20:21            53,575 Untitled.ipynb
01-03-2022  14:37                72 Untitled1.ipynb
27-02-2023  14:30             1,679 Untitled10.ipynb
09-05-2023  10:29                72 Untitled11.ipynb
04-07-2023  13:54             8,651 Untitled12.ipynb
03-08-2023  10:33             3,443 Untitled13.ipynb
07-12-2023  21:37                72 Untitled14.ipynb
03-03-2022  15:56            36,553 Untitled2.ipynb
21-06-2022  15:32               588 Untitled3.ipynb
27-06-2022  22:55             5,082 Untitled4.ipynb
29-06-2022  00:49             5,617 Untitled5.ipynb
30-07-2022  12:48             1,518 Untitled6.ipynb
24-08-2022  17:18            18,874 Untitled7.ipynb
16-10-2022  10:53               588 Untitled8.ipynb
28-11-2022  14:32               796 Untitled9.ipynb
14-10-2022  11:56    <DIR>          updater
02-04-2023  19:10    <DIR>          Videos
             169 File(s)     15,265,013 bytes
              32 Dir(s)  416,152,727,552 bytes free

In [56]:
df.dtypes # columns datatypes

S.no            int64
Name           object
Age             int64
Designation    object
Place          object
Salary          int64
Email          object
dtype: object

In [58]:
df.head() # head gives top 5 rows

   S.no    Name  Age Designation         Place  Salary             Email
0     3   Sanvi    6    Daughter       Chirala   50000   sanvi@gmail.com
1     4   Seivi    6    Daughter       Chirala   50000   seivi@gmail.com
2     6  Ramana   85     Gmother  Narasaraopet   15000  ramana@gmail.com
3     7  Manasa   30      Sister  Narasaraopet   30000  manasa@gmail.com
4     8   Ramya   30   Lawsister     Hyderabad   20000   ramya@gmail.com

In [59]:
df.tail()# this gives last 5 rows from the bottom

   S.no    Name  Age  Designation         Place  Salary             Email
2     6  Ramana   85      Gmother  Narasaraopet   15000  ramana@gmail.com
3     7  Manasa   30       Sister  Narasaraopet   30000  manasa@gmail.com
4     8   Ramya   30    Lawsister     Hyderabad   20000   ramya@gmail.com
5     9  Himani    6  Lawdaughter     Hyderabad   50000  himani@gmail.com
6    10   Tinku   28    Lawsister     Hyderabad   30000   tinku@gmail.com

In [62]:
df.columns # gives column names

Index(['S.no', 'Name', 'Age', 'Designation', 'Place', 'Salary', 'Email'], dtype='object')

In [63]:
df.dtypes # gives types of column values # object= category

S.no            int64
Name           object
Age             int64
Designation    object
Place          object
Salary          int64
Email          object
dtype: object

In [64]:
df

   S.no    Name  Age  Designation         Place  Salary             Email
0     3   Sanvi    6     Daughter       Chirala   50000   sanvi@gmail.com
1     4   Seivi    6     Daughter       Chirala   50000   seivi@gmail.com
2     6  Ramana   85      Gmother  Narasaraopet   15000  ramana@gmail.com
3     7  Manasa   30       Sister  Narasaraopet   30000  manasa@gmail.com
4     8   Ramya   30    Lawsister     Hyderabad   20000   ramya@gmail.com
5     9  Himani    6  Lawdaughter     Hyderabad   50000  himani@gmail.com
6    10   Tinku   28    Lawsister     Hyderabad   30000   tinku@gmail.com

In [66]:
df['Name'] # gives particular column

0     Sanvi
1     Seivi
2    Ramana
3    Manasa
4     Ramya
5    Himani
6     Tinku
Name: Name, dtype: object

In [67]:
a=df['Name']

In [69]:
type(a) # series means entire row or entire column

pandas.core.series.Series

In [72]:
df[['Name','Age','Place']]# must be given in a list for multiple columns

     Name  Age         Place
0   Sanvi    6       Chirala
1   Seivi    6       Chirala
2  Ramana   85  Narasaraopet
3  Manasa   30  Narasaraopet
4   Ramya   30     Hyderabad
5  Himani    6     Hyderabad
6   Tinku   28     Hyderabad

In [73]:
df1=df[['Name','Age','Place']]

In [74]:
df1 # single column series,multi columns dataframe

     Name  Age         Place
0   Sanvi    6       Chirala
1   Seivi    6       Chirala
2  Ramana   85  Narasaraopet
3  Manasa   30  Narasaraopet
4   Ramya   30     Hyderabad
5  Himani    6     Hyderabad
6   Tinku   28     Hyderabad

In [75]:
type(df1)

pandas.core.frame.DataFrame

In [76]:
type(df1['Name'])

pandas.core.series.Series

In [77]:
ls

 Volume in drive C is Windows-SSD
 Volume Serial Number is BA08-EA00

 Directory of C:\Users\91903

07-12-2023  23:02    <DIR>          .
02-04-2023  19:05    <DIR>          ..
31-07-2022  11:32    <DIR>          .astropy
31-07-2022  11:13    <DIR>          .conda
30-11-2022  14:28    <DIR>          .cufflinks
08-05-2023  16:03    <DIR>          .idea
07-12-2023  21:38    <DIR>          .ipynb_checkpoints
21-02-2022  17:38    <DIR>          .ipython
05-03-2022  10:37    <DIR>          .jupyter
31-07-2022  11:40    <DIR>          .matplotlib
03-12-2023  18:07    <DIR>          __pycache__
08-10-2022  22:23            21,198 15th jan exception handling part1.ipynb
26-02-2023  16:06             6,880 16th jan logging.ipynb
25-08-2022  18:29            56,638 18th dec practice.ipynb
18-08-2023  10:20            63,220 19th dec practice.ipynb
11-09-2023  17:09         4,672,436 2023 20dec for loop  and while ipynb.ipynb
11-09-2023  21:28            23,182 2023 21dec ipynb.ipynb
14-09-2023  20:19            30,516 2023 23dec, 8th jan function ipynb.ipynb
01-06-2023  15:09             9,891 2023 6th feb sql day2.ipynb
11-09-2023  13:41            46,294 2023 dec18th set tuple dict ipynb part2.ipynb
11-09-2023  12:26            25,571 2023 dec19th new ipynb if else.ipynb
10-09-2023  22:01            68,837 2023 dec5th str,list new ipynb.ipynb
07-05-2023  19:28           110,238 2023 modules and pycharm.ipynb
11-05-2023  16:37            11,034 2023 sql part 1 feb5th.ipynb
18-08-2023  11:24            21,293 20thdec practice.ipynb
09-04-2022  15:17            23,165 21st dec practice.ipynb
14-10-2022  16:05           100,700 22jan module discussion.ipynb
14-10-2022  17:38             5,648 22jan oops concept.ipynb
30-07-2022  13:00                 0 22jan.py
30-07-2022  13:15                29 22jan1.py
26-06-2022  21:49            22,964 23decrestart.ipynb
11-04-2022  17:05            33,103 23rd dec practice.ipynb
19-10-2022  14:31             8,048 23rd jan oops concept.ipynb
24-08-2022  17:17            34,953 29jan oops.ipynb
25-06-2022  23:46            18,529 8th jan .ipynb
16-10-2022  22:12            38,125 8th jan practice.ipynb
06-10-2022  19:59           105,942 9th jan iterator,generator and filesystem.ipynb
27-06-2022  21:47            69,372 9thjanpractice.ipynb
07-05-2023  18:05                 0 akhil.py
21-02-2022  16:16    <DIR>          anaconda3
02-12-2022  12:49             1,089 API FLASK1.ipynb
04-07-2023  11:44            14,141 Assignment 8.ipynb
04-07-2023  12:15             4,535 Assignment 9.ipynb
28-02-2022  14:55             8,732 Assignment1.ipynb
08-05-2022  18:10            15,719 assignment2.ipynb
22-08-2022  11:36            15,644 Assignment4.ipynb
14-10-2022  11:56    <DIR>          autoCompletion
16-11-2022  14:49           461,474 bank.csv
16-11-2022  14:46           461,474 bank.xls
23-09-2022  02:00             1,007 change.log
02-04-2023  19:10    <DIR>          Contacts
17-01-2022  06:13             4,843 contextMenu.xml
15-11-2022  11:25             5,845 cricket.csv
10-11-2022  11:31             1,560 datastax.ipynb
07-12-2023  21:49               355 day.csv
03-05-2022  12:58            55,145 dec 5th practice.ipynb
25-08-2022  11:55            41,712 dec 5th practice2.ipynb
16-08-2023  13:02            23,803 dec4th practice.ipynb
07-12-2023  22:30               577 Details.csv
01-04-2022  17:58    <DIR>          Documents
07-12-2023  21:50    <DIR>          Downloads
24-04-2023  13:09                22 enapple.ini
13-10-2022  14:04            94,633 exception part2 and logging.ipynb
30-06-2022  21:18            35,344 excpthndlng2.ipynb
28-06-2022  23:07            12,467 exhndlng1.ipynb
02-04-2023  19:10    <DIR>          Favorites
05-10-2022  18:07            89,207 function dec 23rd class practice.ipynb
14-10-2022  11:56    <DIR>          functionList
14-10-2022  12:37               131 funmod1.py
14-10-2022  12:22                 0 funmod2.py
14-10-2022  12:53                94 funmod3.py
14-10-2022  13:00                40 funmod4.py
29-11-2022  22:57         3,078,946 graph 1.ipynb
30-11-2022  17:59         1,789,919 graph2.ipynb
01-12-2023  15:52            56,367 htd 8th jan.ipynb
28-11-2023  15:16                72 hyd 1.ipynb
02-12-2023  18:51            21,791 hyd 15th jan.ipynb
03-12-2023  14:53            51,859 hyd 16th jan.ipynb
30-11-2023  11:30            33,145 hyd 20th dec.ipynb
30-11-2023  20:07            18,848 hyd 21st dec.ipynb
01-12-2023  15:50            28,293 hyd 23rd dec.ipynb
02-12-2023  14:24           140,622 hyd 9th jan.ipynb
29-11-2023  11:37            80,734 hyd dec18th.ipynb
07-12-2023  23:02           134,086 hyd feb 26th pandas.ipynb
03-12-2023  18:14            29,972 hyd jan22nd.ipynb
02-12-2023  15:15           122,373 hyd practice book.ipynb
29-11-2023  14:02            44,090 hyd19th dec.ipynb
03-12-2023  18:13                 0 hydmodule1.py
02-12-2023  13:48               725 hydpara.txt
03-12-2023  14:47             1,074 hydtest.log
02-12-2023  18:18                19 hydtest.txt
02-12-2023  11:59                38 hydtest1.txt
03-12-2023  14:17               567 hydtest2.log
03-12-2023  14:42                 0 hydtest3.log
31-07-2022  12:59            41,601 jan22practice.ipynb
08-11-2022  15:10            12,288 joindb.db
08-11-2022  15:20             8,720 joindb.db-journal
15-11-2022  14:27            35,186 json_res.csv
28-05-2022  07:17           350,341 langs.model.xml
15-08-2021  05:50            35,500 LICENSE
06-10-2022  19:56               147 life.txt
02-04-2023  19:10    <DIR>          Links
14-10-2022  11:56    <DIR>          localization
06-10-2022  19:27             1,934 mahesh.txt
06-10-2022  18:50                51 manasa.txt
13-10-2022  13:52                 0 meethu.log
07-05-2023  18:20               180 mini.py
07-05-2023  17:55                 0 mod1.py
07-05-2023  18:12               130 mod2.py
07-05-2023  17:54                 0 module.py
14-10-2022  11:39                 0 module2.py
27-10-2022  12:23             5,444 mongodb.ipynb
02-04-2023  19:10    <DIR>          Music
30-07-2022  14:06               213 my_module.py
25-10-2022  14:40            10,208 mysql class1.ipynb
15-11-2022  11:15            78,961 NBA.csv
03-12-2023  17:57    <DIR>          notepadplus
05-12-2021  09:58                 0 nppLogNulContentCorruptionIssue.xml
25-09-2022  23:30           232,984 NppShell_06.dll
23-11-2022  17:51            50,763 numpy.ipynb
02-04-2023  19:08    <DIR>          OneDrive
31-07-2022  19:10             5,529 oops basic 22jan.ipynb
01-08-2022  15:53            11,638 oops jan23.ipynb
22-11-2022  21:35           107,440 pandas and numpy.ipynb
10-11-2022  23:34           128,025 pandas1.ipynb
15-11-2022  14:41           619,109 pandas2.ipynb
16-11-2022  15:55           141,613 pandas3.ipynb
17-11-2022  13:14               588 pandas4.ipynb
21-11-2022  19:35           173,487 pandasday4.ipynb
08-11-2022  14:51             8,192 person.db
14-10-2022  11:56    <DIR>          plugins
02-12-2022  11:38    <DIR>          Postman
03-12-2023  10:34                16 priya.txt
07-05-2023  19:11    <DIR>          PycharmProjects
29-09-2022  08:46            10,630 python assignment 5.ipynb
08-10-2022  23:27            14,458 python basic assignment 6.ipynb
15-07-2023  12:52             7,374 python basic programming assignment 11.ipynb
20-07-2023  15:51             6,955 python basic programming assignment 12.ipynb
30-09-2022  18:26             6,317 python basic programming assignment 5.ipynb
07-10-2022  00:13             6,545 python basic programming assignment 6.ipynb
13-10-2022  16:11             4,776 python basic programming assignment 7.ipynb
23-09-2022  16:44             7,776 python basic programming assignment4.ipynb
11-07-2023  15:08             1,383 python programming assignment 10.ipynb
14-07-2023  10:20             9,645 python programming assignment 11.ipynb
04-07-2023  13:58             5,375 python programming assignment 8.ipynb
09-07-2023  17:13            10,556 python programming assignment 9.ipynb
22-08-2022  15:53             4,908 python programming assignment1.ipynb
21-09-2022  14:12             4,130 python programming assignment2.ipynb
22-09-2022  14:06            26,533 python programming assignment3.ipynb
08-11-2022  14:54             8,192 raj.db
08-10-2022  22:02                 9 raji.txt
06-10-2022  19:42                58 rama.txt
27-05-2021  04:27             1,526 readme.txt
21-06-2022  13:45            23,522 restart 20dec.ipynb
21-06-2022  17:07            21,171 restart 21dec.ipynb
17-06-2022  16:30            17,684 restart dec19.ipynb
14-10-2022  12:24                44 rfunmod1.py
13-10-2022  13:29               480 ritu.log
10-11-2022  19:13            14,905 Sales.csv
10-11-2022  19:36               201 sample.csv
10-11-2022  23:15               232 sample.xls.csv
02-04-2023  19:10    <DIR>          Saved Games
30-11-2022  14:30    <DIR>          seaborn-data
02-04-2023  19:10    <DIR>          Searches
13-10-2022  13:35               904 seethu.log
27-05-2021  04:27               965 shortcuts.xml
08-11-2022  19:47            77,976 sql lite 08112022.ipynb
25-10-2022  14:40             8,079 sql part2.ipynb
22-10-2022  23:32             7,994 sql2.ipynb
20-09-2022  22:39           174,773 stylers.model.xml
30-09-2022  17:37             6,652 sudhasirqsadans.ipynb
30-06-2022  22:41               310 test.log
02-12-2023  11:55                 0 test.txt
13-10-2022  12:17                 4 test1
13-10-2022  11:53                22 test1.txt
30-07-2022  13:47               225 test11.py
30-06-2022  22:53               278 test2.log
27-06-2022  13:24                31 test2.txt
14-10-2022  11:29                 0 test3.py
28-06-2022  23:08                11 test3.txt
30-06-2022  16:50                 0 test43.txt
27-06-2022  21:30               551 test5.txt
07-05-2023  18:31               138 testu.py
14-10-2022  11:56    <DIR>          themes
28-02-2022  20:21            53,575 Untitled.ipynb
01-03-2022  14:37                72 Untitled1.ipynb
27-02-2023  14:30             1,679 Untitled10.ipynb
09-05-2023  10:29                72 Untitled11.ipynb
04-07-2023  13:54             8,651 Untitled12.ipynb
03-08-2023  10:33             3,443 Untitled13.ipynb
07-12-2023  21:37                72 Untitled14.ipynb
03-03-2022  15:56            36,553 Untitled2.ipynb
21-06-2022  15:32               588 Untitled3.ipynb
27-06-2022  22:55             5,082 Untitled4.ipynb
29-06-2022  00:49             5,617 Untitled5.ipynb
30-07-2022  12:48             1,518 Untitled6.ipynb
24-08-2022  17:18            18,874 Untitled7.ipynb
16-10-2022  10:53               588 Untitled8.ipynb
28-11-2022  14:32               796 Untitled9.ipynb
14-10-2022  11:56    <DIR>          updater
02-04-2023  19:10    <DIR>          Videos
             169 File(s)     15,302,705 bytes
              32 Dir(s)  416,155,504,640 bytes free

In [78]:
ls

 Volume in drive C is Windows-SSD
 Volume Serial Number is BA08-EA00

 Directory of C:\Users\91903

07-12-2023  23:11    <DIR>          .
02-04-2023  19:05    <DIR>          ..
31-07-2022  11:32    <DIR>          .astropy
31-07-2022  11:13    <DIR>          .conda
30-11-2022  14:28    <DIR>          .cufflinks
08-05-2023  16:03    <DIR>          .idea
07-12-2023  21:38    <DIR>          .ipynb_checkpoints
21-02-2022  17:38    <DIR>          .ipython
05-03-2022  10:37    <DIR>          .jupyter
31-07-2022  11:40    <DIR>          .matplotlib
03-12-2023  18:07    <DIR>          __pycache__
08-10-2022  22:23            21,198 15th jan exception handling part1.ipynb
26-02-2023  16:06             6,880 16th jan logging.ipynb
25-08-2022  18:29            56,638 18th dec practice.ipynb
18-08-2023  10:20            63,220 19th dec practice.ipynb
11-09-2023  17:09         4,672,436 2023 20dec for loop  and while ipynb.ipynb
11-09-2023  21:28            23,182 2023 21dec ipynb.ipynb
14-09-2023  20:19            30,516 2023 23dec, 8th jan function ipynb.ipynb
01-06-2023  15:09             9,891 2023 6th feb sql day2.ipynb
11-09-2023  13:41            46,294 2023 dec18th set tuple dict ipynb part2.ipynb
11-09-2023  12:26            25,571 2023 dec19th new ipynb if else.ipynb
10-09-2023  22:01            68,837 2023 dec5th str,list new ipynb.ipynb
07-05-2023  19:28           110,238 2023 modules and pycharm.ipynb
11-05-2023  16:37            11,034 2023 sql part 1 feb5th.ipynb
18-08-2023  11:24            21,293 20thdec practice.ipynb
09-04-2022  15:17            23,165 21st dec practice.ipynb
14-10-2022  16:05           100,700 22jan module discussion.ipynb
14-10-2022  17:38             5,648 22jan oops concept.ipynb
30-07-2022  13:00                 0 22jan.py
30-07-2022  13:15                29 22jan1.py
26-06-2022  21:49            22,964 23decrestart.ipynb
11-04-2022  17:05            33,103 23rd dec practice.ipynb
19-10-2022  14:31             8,048 23rd jan oops concept.ipynb
24-08-2022  17:17            34,953 29jan oops.ipynb
25-06-2022  23:46            18,529 8th jan .ipynb
16-10-2022  22:12            38,125 8th jan practice.ipynb
06-10-2022  19:59           105,942 9th jan iterator,generator and filesystem.ipynb
27-06-2022  21:47            69,372 9thjanpractice.ipynb
07-05-2023  18:05                 0 akhil.py
21-02-2022  16:16    <DIR>          anaconda3
02-12-2022  12:49             1,089 API FLASK1.ipynb
04-07-2023  11:44            14,141 Assignment 8.ipynb
04-07-2023  12:15             4,535 Assignment 9.ipynb
28-02-2022  14:55             8,732 Assignment1.ipynb
08-05-2022  18:10            15,719 assignment2.ipynb
22-08-2022  11:36            15,644 Assignment4.ipynb
14-10-2022  11:56    <DIR>          autoCompletion
16-11-2022  14:49           461,474 bank.csv
16-11-2022  14:46           461,474 bank.xls
23-09-2022  02:00             1,007 change.log
02-04-2023  19:10    <DIR>          Contacts
17-01-2022  06:13             4,843 contextMenu.xml
15-11-2022  11:25             5,845 cricket.csv
10-11-2022  11:31             1,560 datastax.ipynb
07-12-2023  21:49               355 day.csv
03-05-2022  12:58            55,145 dec 5th practice.ipynb
25-08-2022  11:55            41,712 dec 5th practice2.ipynb
16-08-2023  13:02            23,803 dec4th practice.ipynb
07-12-2023  22:30               577 Details.csv
01-04-2022  17:58    <DIR>          Documents
07-12-2023  23:11    <DIR>          Downloads
24-04-2023  13:09                22 enapple.ini
13-10-2022  14:04            94,633 exception part2 and logging.ipynb
30-06-2022  21:18            35,344 excpthndlng2.ipynb
28-06-2022  23:07            12,467 exhndlng1.ipynb
02-04-2023  19:10    <DIR>          Favorites
05-10-2022  18:07            89,207 function dec 23rd class practice.ipynb
14-10-2022  11:56    <DIR>          functionList
14-10-2022  12:37               131 funmod1.py
14-10-2022  12:22                 0 funmod2.py
14-10-2022  12:53                94 funmod3.py
14-10-2022  13:00                40 funmod4.py
29-11-2022  22:57         3,078,946 graph 1.ipynb
30-11-2022  17:59         1,789,919 graph2.ipynb
01-12-2023  15:52            56,367 htd 8th jan.ipynb
28-11-2023  15:16                72 hyd 1.ipynb
02-12-2023  18:51            21,791 hyd 15th jan.ipynb
03-12-2023  14:53            51,859 hyd 16th jan.ipynb
30-11-2023  11:30            33,145 hyd 20th dec.ipynb
30-11-2023  20:07            18,848 hyd 21st dec.ipynb
01-12-2023  15:50            28,293 hyd 23rd dec.ipynb
02-12-2023  14:24           140,622 hyd 9th jan.ipynb
29-11-2023  11:37            80,734 hyd dec18th.ipynb
07-12-2023  23:04           147,962 hyd feb 26th pandas.ipynb
03-12-2023  18:14            29,972 hyd jan22nd.ipynb
02-12-2023  15:15           122,373 hyd practice book.ipynb
29-11-2023  14:02            44,090 hyd19th dec.ipynb
03-12-2023  18:13                 0 hydmodule1.py
02-12-2023  13:48               725 hydpara.txt
03-12-2023  14:47             1,074 hydtest.log
02-12-2023  18:18                19 hydtest.txt
02-12-2023  11:59                38 hydtest1.txt
03-12-2023  14:17               567 hydtest2.log
03-12-2023  14:42                 0 hydtest3.log
31-07-2022  12:59            41,601 jan22practice.ipynb
08-11-2022  15:10            12,288 joindb.db
08-11-2022  15:20             8,720 joindb.db-journal
15-11-2022  14:27            35,186 json_res.csv
28-05-2022  07:17           350,341 langs.model.xml
15-08-2021  05:50            35,500 LICENSE
06-10-2022  19:56               147 life.txt
02-04-2023  19:10    <DIR>          Links
14-10-2022  11:56    <DIR>          localization
06-10-2022  19:27             1,934 mahesh.txt
06-10-2022  18:50                51 manasa.txt
13-10-2022  13:52                 0 meethu.log
07-05-2023  18:20               180 mini.py
07-05-2023  17:55                 0 mod1.py
07-05-2023  18:12               130 mod2.py
07-05-2023  17:54                 0 module.py
14-10-2022  11:39                 0 module2.py
27-10-2022  12:23             5,444 mongodb.ipynb
02-04-2023  19:10    <DIR>          Music
30-07-2022  14:06               213 my_module.py
25-10-2022  14:40            10,208 mysql class1.ipynb
15-11-2022  11:15            78,961 NBA.csv
03-12-2023  17:57    <DIR>          notepadplus
05-12-2021  09:58                 0 nppLogNulContentCorruptionIssue.xml
25-09-2022  23:30           232,984 NppShell_06.dll
23-11-2022  17:51            50,763 numpy.ipynb
02-04-2023  19:08    <DIR>          OneDrive
31-07-2022  19:10             5,529 oops basic 22jan.ipynb
01-08-2022  15:53            11,638 oops jan23.ipynb
22-11-2022  21:35           107,440 pandas and numpy.ipynb
10-11-2022  23:34           128,025 pandas1.ipynb
15-11-2022  14:41           619,109 pandas2.ipynb
16-11-2022  15:55           141,613 pandas3.ipynb
17-11-2022  13:14               588 pandas4.ipynb
21-11-2022  19:35           173,487 pandasday4.ipynb
08-11-2022  14:51             8,192 person.db
14-10-2022  11:56    <DIR>          plugins
02-12-2022  11:38    <DIR>          Postman
03-12-2023  10:34                16 priya.txt
07-05-2023  19:11    <DIR>          PycharmProjects
29-09-2022  08:46            10,630 python assignment 5.ipynb
08-10-2022  23:27            14,458 python basic assignment 6.ipynb
15-07-2023  12:52             7,374 python basic programming assignment 11.ipynb
20-07-2023  15:51             6,955 python basic programming assignment 12.ipynb
30-09-2022  18:26             6,317 python basic programming assignment 5.ipynb
07-10-2022  00:13             6,545 python basic programming assignment 6.ipynb
13-10-2022  16:11             4,776 python basic programming assignment 7.ipynb
23-09-2022  16:44             7,776 python basic programming assignment4.ipynb
11-07-2023  15:08             1,383 python programming assignment 10.ipynb
14-07-2023  10:20             9,645 python programming assignment 11.ipynb
04-07-2023  13:58             5,375 python programming assignment 8.ipynb
09-07-2023  17:13            10,556 python programming assignment 9.ipynb
22-08-2022  15:53             4,908 python programming assignment1.ipynb
21-09-2022  14:12             4,130 python programming assignment2.ipynb
22-09-2022  14:06            26,533 python programming assignment3.ipynb
08-11-2022  14:54             8,192 raj.db
08-10-2022  22:02                 9 raji.txt
06-10-2022  19:42                58 rama.txt
27-05-2021  04:27             1,526 readme.txt
21-06-2022  13:45            23,522 restart 20dec.ipynb
21-06-2022  17:07            21,171 restart 21dec.ipynb
17-06-2022  16:30            17,684 restart dec19.ipynb
14-10-2022  12:24                44 rfunmod1.py
13-10-2022  13:29               480 ritu.log
10-11-2022  19:13            14,905 Sales.csv
10-11-2022  19:36               201 sample.csv
10-11-2022  23:15               232 sample.xls.csv
07-12-2023  23:10           167,424 sample-xls-file-for-testing.xls
02-04-2023  19:10    <DIR>          Saved Games
30-11-2022  14:30    <DIR>          seaborn-data
02-04-2023  19:10    <DIR>          Searches
13-10-2022  13:35               904 seethu.log
27-05-2021  04:27               965 shortcuts.xml
08-11-2022  19:47            77,976 sql lite 08112022.ipynb
25-10-2022  14:40             8,079 sql part2.ipynb
22-10-2022  23:32             7,994 sql2.ipynb
20-09-2022  22:39           174,773 stylers.model.xml
30-09-2022  17:37             6,652 sudhasirqsadans.ipynb
30-06-2022  22:41               310 test.log
02-12-2023  11:55                 0 test.txt
13-10-2022  12:17                 4 test1
13-10-2022  11:53                22 test1.txt
30-07-2022  13:47               225 test11.py
30-06-2022  22:53               278 test2.log
27-06-2022  13:24                31 test2.txt
14-10-2022  11:29                 0 test3.py
28-06-2022  23:08                11 test3.txt
30-06-2022  16:50                 0 test43.txt
27-06-2022  21:30               551 test5.txt
07-05-2023  18:31               138 testu.py
14-10-2022  11:56    <DIR>          themes
28-02-2022  20:21            53,575 Untitled.ipynb
01-03-2022  14:37                72 Untitled1.ipynb
27-02-2023  14:30             1,679 Untitled10.ipynb
09-05-2023  10:29                72 Untitled11.ipynb
04-07-2023  13:54             8,651 Untitled12.ipynb
03-08-2023  10:33             3,443 Untitled13.ipynb
07-12-2023  21:37                72 Untitled14.ipynb
03-03-2022  15:56            36,553 Untitled2.ipynb
21-06-2022  15:32               588 Untitled3.ipynb
27-06-2022  22:55             5,082 Untitled4.ipynb
29-06-2022  00:49             5,617 Untitled5.ipynb
30-07-2022  12:48             1,518 Untitled6.ipynb
24-08-2022  17:18            18,874 Untitled7.ipynb
16-10-2022  10:53               588 Untitled8.ipynb
28-11-2022  14:32               796 Untitled9.ipynb
14-10-2022  11:56    <DIR>          updater
02-04-2023  19:10    <DIR>          Videos
             170 File(s)     15,484,005 bytes
              32 Dir(s)  414,360,485,888 bytes free

In [79]:
pd.read_excel('sample-xls-file-for-testing.xls')

,Segment,Country,Product,Discount Band,Units Sold,Manufacturing Price,Sale Price,Gross Sales,Discounts,Sales,COGS,Profit,Date,Month Number,Month Name,Year
0,Government,Canada,Carretera,None,1618.5,3,20,32370.0,0.00,32370.00,16185.0,16185.00,2014-01-01,1,January,2014
1,Government,Germany,Carretera,None,1321.0,3,20,26420.0,0.00,26420.00,13210.0,13210.00,2014-01-01,1,January,2014
2,Midmarket,France,Carretera,None,2178.0,3,15,32670.0,0.00,32670.00,21780.0,10890.00,2014-06-01,6,June,2014
3,Midmarket,Germany,Carretera,None,888.0,3,15,13320.0,0.00,13320.00,8880.0,4440.00,2014-06-01,6,June,2014
4,Midmarket,Mexico,Carretera,None,2470.0,3,15,37050.0,0.00,37050.00,24700.0,12350.00,2014-06-01,6,June,2014
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
695,Small Business,France,Amarilla,High,2475.0,260,300,742500.0,111375.00,631125.00,618750.0,12375.00,2014-03-01,3,March,2014
696,Small Business,Mexico,Amarilla,High,546.0,260,300,163800.0,24570.00,139230.00,136500.0,2730.00,2014-10-01,10,October,2014
697,Government,Mexico,Montana,High,1368.0,5,7,9576.0,1436.40,8139.60,6840.0,1299.60,2014-02-01,2,February,2014
698,Government,Canada,Paseo,High,723.0,10,7,5061.0,759.15,4301.85,3615.0,686.85,2014-04-01,4,April,2014
699,Channel Partners,United States of America,VTT,High,1806.0,250,12,21672.0,3250.80,18421.20,5418.0,13003.20,2014-05-01,5,May,2014

In [80]:
df=pd.read_excel('sample-xls-file-for-testing.xls')

In [81]:
df

,Segment,Country,Product,Discount Band,Units Sold,Manufacturing Price,Sale Price,Gross Sales,Discounts,Sales,COGS,Profit,Date,Month Number,Month Name,Year
0,Government,Canada,Carretera,None,1618.5,3,20,32370.0,0.00,32370.00,16185.0,16185.00,2014-01-01,1,January,2014
1,Government,Germany,Carretera,None,1321.0,3,20,26420.0,0.00,26420.00,13210.0,13210.00,2014-01-01,1,January,2014
2,Midmarket,France,Carretera,None,2178.0,3,15,32670.0,0.00,32670.00,21780.0,10890.00,2014-06-01,6,June,2014
3,Midmarket,Germany,Carretera,None,888.0,3,15,13320.0,0.00,13320.00,8880.0,4440.00,2014-06-01,6,June,2014
4,Midmarket,Mexico,Carretera,None,2470.0,3,15,37050.0,0.00,37050.00,24700.0,12350.00,2014-06-01,6,June,2014
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
695,Small Business,France,Amarilla,High,2475.0,260,300,742500.0,111375.00,631125.00,618750.0,12375.00,2014-03-01,3,March,2014
696,Small Business,Mexico,Amarilla,High,546.0,260,300,163800.0,24570.00,139230.00,136500.0,2730.00,2014-10-01,10,October,2014
697,Government,Mexico,Montana,High,1368.0,5,7,9576.0,1436.40,8139.60,6840.0,1299.60,2014-02-01,2,February,2014
698,Government,Canada,Paseo,High,723.0,10,7,5061.0,759.15,4301.85,3615.0,686.85,2014-04-01,4,April,2014
699,Channel Partners,United States of America,VTT,High,1806.0,250,12,21672.0,3250.80,18421.20,5418.0,13003.20,2014-05-01,5,May,2014

In [82]:
df.keys()

Index(['Segment', 'Country', 'Product', 'Discount Band', 'Units Sold',
       'Manufacturing Price', 'Sale Price', 'Gross Sales', 'Discounts',
       ' Sales', 'COGS', 'Profit', 'Date', 'Month Number', 'Month Name',
       'Year'],
      dtype='object')

In [83]:
df.columns

Index(['Segment', 'Country', 'Product', 'Discount Band', 'Units Sold',
       'Manufacturing Price', 'Sale Price', 'Gross Sales', 'Discounts',
       ' Sales', 'COGS', 'Profit', 'Date', 'Month Number', 'Month Name',
       'Year'],
      dtype='object')

In [84]:
# df.keys() and df.columns gives the same output

In [87]:
df.sheet_names

AttributeError: 'DataFrame' object has no attribute 'sheet_names'

In [88]:
# if excelsheet have more than one sheet the above
# tab works

In [90]:
for i in df.sheet_names:
    pd.read_excel('sample-xls-file-for-testing.xls',sheet_name=i)

AttributeError: 'DataFrame' object has no attribute 'sheet_names'

In [91]:
pd.read_csv('https://gist.githubusercontent.com/fyyying/4aa5b471860321d7b47fd881898162b7/raw/6907bb3a38bfbb6fccf3a8b1edfb90e39714d14f/titanic_dataset.csv')

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S
...,...,...,...,...,...,...,...,...,...,...,...,...
886,887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.0000,NaN,S
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.0000,B42,S
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.4500,NaN,S
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,C148,C
890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.7500,NaN,Q

In [92]:
# how to bring dataset from html page

In [94]:
pd.read_html('https://www.basketball-reference.com/leagues/NBA_2015_totals.html')

[      Rk          Player Pos Age   Tm   G  GS    MP   FG  FGA  ...   FT%  ORB  \
 0      1      Quincy Acy  PF  24  NYK  68  22  1287  152  331  ...  .784   79
 1      2    Jordan Adams  SG  20  MEM  30   0   248   35   86  ...  .609    9
 2      3    Steven Adams   C  21  OKC  70  67  1771  217  399  ...  .502  199
 3      4     Jeff Adrien  PF  28  MIN  17   0   215   19   44  ...  .579   23
 4      5   Arron Afflalo  SG  29  TOT  78  72  2502  375  884  ...  .843   27
 ..   ...             ...  ..  ..  ...  ..  ..   ...  ...  ...  ...   ...  ...
 670  490  Thaddeus Young  PF  26  TOT  76  68  2434  451  968  ...  .655  127
 671  490  Thaddeus Young  PF  26  MIN  48  48  1605  289  641  ...  .682   75
 672  490  Thaddeus Young  PF  26  BRK  28  20   829  162  327  ...  .606   52
 673  491     Cody Zeller   C  22  CHO  62  45  1487  172  373  ...  .774   97
 674  492    Tyler Zeller   C  25  BOS  82  59  1731  340  619  ...  .823  146

      DRB  TRB  AST  STL BLK  TOV   PF   PTS
 0    222  301   68   27  22   60  147   398
 1     19   28   16   16   7   14   24    94
 2    324  523   66   38  86   99  222   537
 3     54   77   15    4   9    9   30    60
 4    220  247  129   41   7  116  167  1035
 ..   ...  ...  ...  ...  ..  ...  ...   ...
 670  284  411  173  124  25  117  171  1071
 671  170  245  135   86  17   75  115   685
 672  114  166   38   38   8   42   56   386
 673  265  362  100   34  49   62  156   472
 674  319  465  113   18  52   76  205   833

 [675 rows x 30 columns]]

In [95]:
df=pd.read_html('https://www.basketball-reference.com/leagues/NBA_2015_totals.html')

In [96]:
df

[      Rk          Player Pos Age   Tm   G  GS    MP   FG  FGA  ...   FT%  ORB  \
 0      1      Quincy Acy  PF  24  NYK  68  22  1287  152  331  ...  .784   79
 1      2    Jordan Adams  SG  20  MEM  30   0   248   35   86  ...  .609    9
 2      3    Steven Adams   C  21  OKC  70  67  1771  217  399  ...  .502  199
 3      4     Jeff Adrien  PF  28  MIN  17   0   215   19   44  ...  .579   23
 4      5   Arron Afflalo  SG  29  TOT  78  72  2502  375  884  ...  .843   27
 ..   ...             ...  ..  ..  ...  ..  ..   ...  ...  ...  ...   ...  ...
 670  490  Thaddeus Young  PF  26  TOT  76  68  2434  451  968  ...  .655  127
 671  490  Thaddeus Young  PF  26  MIN  48  48  1605  289  641  ...  .682   75
 672  490  Thaddeus Young  PF  26  BRK  28  20   829  162  327  ...  .606   52
 673  491     Cody Zeller   C  22  CHO  62  45  1487  172  373  ...  .774   97
 674  492    Tyler Zeller   C  25  BOS  82  59  1731  340  619  ...  .823  146

      DRB  TRB  AST  STL BLK  TOV   PF   PTS
 0    222  301   68   27  22   60  147   398
 1     19   28   16   16   7   14   24    94
 2    324  523   66   38  86   99  222   537
 3     54   77   15    4   9    9   30    60
 4    220  247  129   41   7  116  167  1035
 ..   ...  ...  ...  ...  ..  ...  ...   ...
 670  284  411  173  124  25  117  171  1071
 671  170  245  135   86  17   75  115   685
 672  114  166   38   38   8   42   56   386
 673  265  362  100   34  49   62  156   472
 674  319  465  113   18  52   76  205   833

 [675 rows x 30 columns]]

In [97]:
# the above data is in list format

In [98]:
type(df)

list

In [99]:
df

[      Rk          Player Pos Age   Tm   G  GS    MP   FG  FGA  ...   FT%  ORB  \
 0      1      Quincy Acy  PF  24  NYK  68  22  1287  152  331  ...  .784   79
 1      2    Jordan Adams  SG  20  MEM  30   0   248   35   86  ...  .609    9
 2      3    Steven Adams   C  21  OKC  70  67  1771  217  399  ...  .502  199
 3      4     Jeff Adrien  PF  28  MIN  17   0   215   19   44  ...  .579   23
 4      5   Arron Afflalo  SG  29  TOT  78  72  2502  375  884  ...  .843   27
 ..   ...             ...  ..  ..  ...  ..  ..   ...  ...  ...  ...   ...  ...
 670  490  Thaddeus Young  PF  26  TOT  76  68  2434  451  968  ...  .655  127
 671  490  Thaddeus Young  PF  26  MIN  48  48  1605  289  641  ...  .682   75
 672  490  Thaddeus Young  PF  26  BRK  28  20   829  162  327  ...  .606   52
 673  491     Cody Zeller   C  22  CHO  62  45  1487  172  373  ...  .774   97
 674  492    Tyler Zeller   C  25  BOS  82  59  1731  340  619  ...  .823  146

      DRB  TRB  AST  STL BLK  TOV   PF   PTS
 0    222  301   68   27  22   60  147   398
 1     19   28   16   16   7   14   24    94
 2    324  523   66   38  86   99  222   537
 3     54   77   15    4   9    9   30    60
 4    220  247  129   41   7  116  167  1035
 ..   ...  ...  ...  ...  ..  ...  ...   ...
 670  284  411  173  124  25  117  171  1071
 671  170  245  135   86  17   75  115   685
 672  114  166   38   38   8   42   56   386
 673  265  362  100   34  49   62  156   472
 674  319  465  113   18  52   76  205   833

 [675 rows x 30 columns]]

In [100]:
len(df)

1

In [101]:
df[0]

,Rk,Player,Pos,Age,Tm,G,GS,MP,FG,FGA,...,FT%,ORB,DRB,TRB,AST,STL,BLK,TOV,PF,PTS
0,1,Quincy Acy,PF,24,NYK,68,22,1287,152,331,...,.784,79,222,301,68,27,22,60,147,398
1,2,Jordan Adams,SG,20,MEM,30,0,248,35,86,...,.609,9,19,28,16,16,7,14,24,94
2,3,Steven Adams,C,21,OKC,70,67,1771,217,399,...,.502,199,324,523,66,38,86,99,222,537
3,4,Jeff Adrien,PF,28,MIN,17,0,215,19,44,...,.579,23,54,77,15,4,9,9,30,60
4,5,Arron Afflalo,SG,29,TOT,78,72,2502,375,884,...,.843,27,220,247,129,41,7,116,167,1035
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
670,490,Thaddeus Young,PF,26,TOT,76,68,2434,451,968,...,.655,127,284,411,173,124,25,117,171,1071
671,490,Thaddeus Young,PF,26,MIN,48,48,1605,289,641,...,.682,75,170,245,135,86,17,75,115,685
672,490,Thaddeus Young,PF,26,BRK,28,20,829,162,327,...,.606,52,114,166,38,38,8,42,56,386
673,491,Cody Zeller,C,22,CHO,62,45,1487,172,373,...,.774,97,265,362,100,34,49,62,156,472
674,492,Tyler Zeller,C,25,BOS,82,59,1731,340,619,...,.823,146,319,465,113,18,52,76,205,833

In [102]:
type(df[0])

pandas.core.frame.DataFrame

In [103]:
df1=df[0]

In [104]:
df1

,Rk,Player,Pos,Age,Tm,G,GS,MP,FG,FGA,...,FT%,ORB,DRB,TRB,AST,STL,BLK,TOV,PF,PTS
0,1,Quincy Acy,PF,24,NYK,68,22,1287,152,331,...,.784,79,222,301,68,27,22,60,147,398
1,2,Jordan Adams,SG,20,MEM,30,0,248,35,86,...,.609,9,19,28,16,16,7,14,24,94
2,3,Steven Adams,C,21,OKC,70,67,1771,217,399,...,.502,199,324,523,66,38,86,99,222,537
3,4,Jeff Adrien,PF,28,MIN,17,0,215,19,44,...,.579,23,54,77,15,4,9,9,30,60
4,5,Arron Afflalo,SG,29,TOT,78,72,2502,375,884,...,.843,27,220,247,129,41,7,116,167,1035
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
670,490,Thaddeus Young,PF,26,TOT,76,68,2434,451,968,...,.655,127,284,411,173,124,25,117,171,1071
671,490,Thaddeus Young,PF,26,MIN,48,48,1605,289,641,...,.682,75,170,245,135,86,17,75,115,685
672,490,Thaddeus Young,PF,26,BRK,28,20,829,162,327,...,.606,52,114,166,38,38,8,42,56,386
673,491,Cody Zeller,C,22,CHO,62,45,1487,172,373,...,.774,97,265,362,100,34,49,62,156,472
674,492,Tyler Zeller,C,25,BOS,82,59,1731,340,619,...,.823,146,319,465,113,18,52,76,205,833

In [105]:
df1.columns

Index(['Rk', 'Player', 'Pos', 'Age', 'Tm', 'G', 'GS', 'MP', 'FG', 'FGA', 'FG%',
       '3P', '3PA', '3P%', '2P', '2PA', '2P%', 'eFG%', 'FT', 'FTA', 'FT%',
       'ORB', 'DRB', 'TRB', 'AST', 'STL', 'BLK', 'TOV', 'PF', 'PTS'],
      dtype='object')

In [106]:
df1.head()

,Rk,Player,Pos,Age,Tm,G,GS,MP,FG,FGA,...,FT%,ORB,DRB,TRB,AST,STL,BLK,TOV,PF,PTS
0,1,Quincy Acy,PF,24,NYK,68,22,1287,152,331,...,.784,79,222,301,68,27,22,60,147,398
1,2,Jordan Adams,SG,20,MEM,30,0,248,35,86,...,.609,9,19,28,16,16,7,14,24,94
2,3,Steven Adams,C,21,OKC,70,67,1771,217,399,...,.502,199,324,523,66,38,86,99,222,537
3,4,Jeff Adrien,PF,28,MIN,17,0,215,19,44,...,.579,23,54,77,15,4,9,9,30,60
4,5,Arron Afflalo,SG,29,TOT,78,72,2502,375,884,...,.843,27,220,247,129,41,7,116,167,1035

In [107]:
df1.tail()

,Rk,Player,Pos,Age,Tm,G,GS,MP,FG,FGA,...,FT%,ORB,DRB,TRB,AST,STL,BLK,TOV,PF,PTS
670,490,Thaddeus Young,PF,26,TOT,76,68,2434,451,968,...,.655,127,284,411,173,124,25,117,171,1071
671,490,Thaddeus Young,PF,26,MIN,48,48,1605,289,641,...,.682,75,170,245,135,86,17,75,115,685
672,490,Thaddeus Young,PF,26,BRK,28,20,829,162,327,...,.606,52,114,166,38,38,8,42,56,386
673,491,Cody Zeller,C,22,CHO,62,45,1487,172,373,...,.774,97,265,362,100,34,49,62,156,472
674,492,Tyler Zeller,C,25,BOS,82,59,1731,340,619,...,.823,146,319,465,113,18,52,76,205,833

In [108]:
df1.head(3)

,Rk,Player,Pos,Age,Tm,G,GS,MP,FG,FGA,...,FT%,ORB,DRB,TRB,AST,STL,BLK,TOV,PF,PTS
0,1,Quincy Acy,PF,24,NYK,68,22,1287,152,331,...,.784,79,222,301,68,27,22,60,147,398
1,2,Jordan Adams,SG,20,MEM,30,0,248,35,86,...,.609,9,19,28,16,16,7,14,24,94
2,3,Steven Adams,C,21,OKC,70,67,1771,217,399,...,.502,199,324,523,66,38,86,99,222,537

In [109]:
df1.tail(3)

,Rk,Player,Pos,Age,Tm,G,GS,MP,FG,FGA,...,FT%,ORB,DRB,TRB,AST,STL,BLK,TOV,PF,PTS
672,490,Thaddeus Young,PF,26,BRK,28,20,829,162,327,...,.606,52,114,166,38,38,8,42,56,386
673,491,Cody Zeller,C,22,CHO,62,45,1487,172,373,...,.774,97,265,362,100,34,49,62,156,472
674,492,Tyler Zeller,C,25,BOS,82,59,1731,340,619,...,.823,146,319,465,113,18,52,76,205,833

In [111]:
df1.dtypes

Rk        object
Player    object
Pos       object
Age       object
Tm        object
G         object
GS        object
MP        object
FG        object
FGA       object
FG%       object
3P        object
3PA       object
3P%       object
2P        object
2PA       object
2P%       object
eFG%      object
FT        object
FTA       object
FT%       object
ORB       object
DRB       object
TRB       object
AST       object
STL       object
BLK       object
TOV       object
PF        object
PTS       object
dtype: object

In [112]:
df1[['Age','GS']]

    Age  GS
0    24  22
1    20   0
2    21  67
3    28   0
4    29  72
..   ..  ..
670  26  68
671  26  48
672  26  20
673  22  45
674  25  59

[675 rows x 2 columns]

In [113]:
df1

,Rk,Player,Pos,Age,Tm,G,GS,MP,FG,FGA,...,FT%,ORB,DRB,TRB,AST,STL,BLK,TOV,PF,PTS
0,1,Quincy Acy,PF,24,NYK,68,22,1287,152,331,...,.784,79,222,301,68,27,22,60,147,398
1,2,Jordan Adams,SG,20,MEM,30,0,248,35,86,...,.609,9,19,28,16,16,7,14,24,94
2,3,Steven Adams,C,21,OKC,70,67,1771,217,399,...,.502,199,324,523,66,38,86,99,222,537
3,4,Jeff Adrien,PF,28,MIN,17,0,215,19,44,...,.579,23,54,77,15,4,9,9,30,60
4,5,Arron Afflalo,SG,29,TOT,78,72,2502,375,884,...,.843,27,220,247,129,41,7,116,167,1035
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
670,490,Thaddeus Young,PF,26,TOT,76,68,2434,451,968,...,.655,127,284,411,173,124,25,117,171,1071
671,490,Thaddeus Young,PF,26,MIN,48,48,1605,289,641,...,.682,75,170,245,135,86,17,75,115,685
672,490,Thaddeus Young,PF,26,BRK,28,20,829,162,327,...,.606,52,114,166,38,38,8,42,56,386
673,491,Cody Zeller,C,22,CHO,62,45,1487,172,373,...,.774,97,265,362,100,34,49,62,156,472
674,492,Tyler Zeller,C,25,BOS,82,59,1731,340,619,...,.823,146,319,465,113,18,52,76,205,833

In [114]:
df1.to_csv('NBA.csv',index=False)

In [115]:
ls

 Volume in drive C is Windows-SSD
 Volume Serial Number is BA08-EA00

 Directory of C:\Users\91903

07-12-2023  23:30    <DIR>          .
02-04-2023  19:05    <DIR>          ..
31-07-2022  11:32    <DIR>          .astropy
31-07-2022  11:13    <DIR>          .conda
30-11-2022  14:28    <DIR>          .cufflinks
08-05-2023  16:03    <DIR>          .idea
07-12-2023  21:38    <DIR>          .ipynb_checkpoints
21-02-2022  17:38    <DIR>          .ipython
05-03-2022  10:37    <DIR>          .jupyter
31-07-2022  11:40    <DIR>          .matplotlib
03-12-2023  18:07    <DIR>          __pycache__
08-10-2022  22:23            21,198 15th jan exception handling part1.ipynb
26-02-2023  16:06             6,880 16th jan logging.ipynb
25-08-2022  18:29            56,638 18th dec practice.ipynb
18-08-2023  10:20            63,220 19th dec practice.ipynb
11-09-2023  17:09         4,672,436 2023 20dec for loop  and while ipynb.ipynb
11-09-2023  21:28            23,182 2023 21dec ipynb.ipynb
14-09-2023  20:19            30,516 2023 23dec, 8th jan function ipynb.ipynb
01-06-2023  15:09             9,891 2023 6th feb sql day2.ipynb
11-09-2023  13:41            46,294 2023 dec18th set tuple dict ipynb part2.ipynb
11-09-2023  12:26            25,571 2023 dec19th new ipynb if else.ipynb
10-09-2023  22:01            68,837 2023 dec5th str,list new ipynb.ipynb
07-05-2023  19:28           110,238 2023 modules and pycharm.ipynb
11-05-2023  16:37            11,034 2023 sql part 1 feb5th.ipynb
18-08-2023  11:24            21,293 20thdec practice.ipynb
09-04-2022  15:17            23,165 21st dec practice.ipynb
14-10-2022  16:05           100,700 22jan module discussion.ipynb
14-10-2022  17:38             5,648 22jan oops concept.ipynb
30-07-2022  13:00                 0 22jan.py
30-07-2022  13:15                29 22jan1.py
26-06-2022  21:49            22,964 23decrestart.ipynb
11-04-2022  17:05            33,103 23rd dec practice.ipynb
19-10-2022  14:31             8,048 23rd jan oops concept.ipynb
24-08-2022  17:17            34,953 29jan oops.ipynb
25-06-2022  23:46            18,529 8th jan .ipynb
16-10-2022  22:12            38,125 8th jan practice.ipynb
06-10-2022  19:59           105,942 9th jan iterator,generator and filesystem.ipynb
27-06-2022  21:47            69,372 9thjanpractice.ipynb
07-05-2023  18:05                 0 akhil.py
21-02-2022  16:16    <DIR>          anaconda3
02-12-2022  12:49             1,089 API FLASK1.ipynb
04-07-2023  11:44            14,141 Assignment 8.ipynb
04-07-2023  12:15             4,535 Assignment 9.ipynb
28-02-2022  14:55             8,732 Assignment1.ipynb
08-05-2022  18:10            15,719 assignment2.ipynb
22-08-2022  11:36            15,644 Assignment4.ipynb
14-10-2022  11:56    <DIR>          autoCompletion
16-11-2022  14:49           461,474 bank.csv
16-11-2022  14:46           461,474 bank.xls
23-09-2022  02:00             1,007 change.log
02-04-2023  19:10    <DIR>          Contacts
17-01-2022  06:13             4,843 contextMenu.xml
15-11-2022  11:25             5,845 cricket.csv
10-11-2022  11:31             1,560 datastax.ipynb
07-12-2023  21:49               355 day.csv
03-05-2022  12:58            55,145 dec 5th practice.ipynb
25-08-2022  11:55            41,712 dec 5th practice2.ipynb
16-08-2023  13:02            23,803 dec4th practice.ipynb
07-12-2023  22:30               577 Details.csv
01-04-2022  17:58    <DIR>          Documents
07-12-2023  23:11    <DIR>          Downloads
24-04-2023  13:09                22 enapple.ini
13-10-2022  14:04            94,633 exception part2 and logging.ipynb
30-06-2022  21:18            35,344 excpthndlng2.ipynb
28-06-2022  23:07            12,467 exhndlng1.ipynb
02-04-2023  19:10    <DIR>          Favorites
05-10-2022  18:07            89,207 function dec 23rd class practice.ipynb
14-10-2022  11:56    <DIR>          functionList
14-10-2022  12:37               131 funmod1.py
14-10-2022  12:22                 0 funmod2.py
14-10-2022  12:53                94 funmod3.py
14-10-2022  13:00                40 funmod4.py
29-11-2022  22:57         3,078,946 graph 1.ipynb
30-11-2022  17:59         1,789,919 graph2.ipynb
01-12-2023  15:52            56,367 htd 8th jan.ipynb
28-11-2023  15:16                72 hyd 1.ipynb
02-12-2023  18:51            21,791 hyd 15th jan.ipynb
03-12-2023  14:53            51,859 hyd 16th jan.ipynb
30-11-2023  11:30            33,145 hyd 20th dec.ipynb
30-11-2023  20:07            18,848 hyd 21st dec.ipynb
01-12-2023  15:50            28,293 hyd 23rd dec.ipynb
02-12-2023  14:24           140,622 hyd 9th jan.ipynb
29-11-2023  11:37            80,734 hyd dec18th.ipynb
07-12-2023  23:30           255,726 hyd feb 26th pandas.ipynb
03-12-2023  18:14            29,972 hyd jan22nd.ipynb
02-12-2023  15:15           122,373 hyd practice book.ipynb
29-11-2023  14:02            44,090 hyd19th dec.ipynb
03-12-2023  18:13                 0 hydmodule1.py
02-12-2023  13:48               725 hydpara.txt
03-12-2023  14:47             1,074 hydtest.log
02-12-2023  18:18                19 hydtest.txt
02-12-2023  11:59                38 hydtest1.txt
03-12-2023  14:17               567 hydtest2.log
03-12-2023  14:42                 0 hydtest3.log
31-07-2022  12:59            41,601 jan22practice.ipynb
08-11-2022  15:10            12,288 joindb.db
08-11-2022  15:20             8,720 joindb.db-journal
15-11-2022  14:27            35,186 json_res.csv
28-05-2022  07:17           350,341 langs.model.xml
15-08-2021  05:50            35,500 LICENSE
06-10-2022  19:56               147 life.txt
02-04-2023  19:10    <DIR>          Links
14-10-2022  11:56    <DIR>          localization
06-10-2022  19:27             1,934 mahesh.txt
06-10-2022  18:50                51 manasa.txt
13-10-2022  13:52                 0 meethu.log
07-05-2023  18:20               180 mini.py
07-05-2023  17:55                 0 mod1.py
07-05-2023  18:12               130 mod2.py
07-05-2023  17:54                 0 module.py
14-10-2022  11:39                 0 module2.py
27-10-2022  12:23             5,444 mongodb.ipynb
02-04-2023  19:10    <DIR>          Music
30-07-2022  14:06               213 my_module.py
25-10-2022  14:40            10,208 mysql class1.ipynb
07-12-2023  23:32            78,962 NBA.csv
03-12-2023  17:57    <DIR>          notepadplus
05-12-2021  09:58                 0 nppLogNulContentCorruptionIssue.xml
25-09-2022  23:30           232,984 NppShell_06.dll
23-11-2022  17:51            50,763 numpy.ipynb
02-04-2023  19:08    <DIR>          OneDrive
31-07-2022  19:10             5,529 oops basic 22jan.ipynb
01-08-2022  15:53            11,638 oops jan23.ipynb
22-11-2022  21:35           107,440 pandas and numpy.ipynb
10-11-2022  23:34           128,025 pandas1.ipynb
15-11-2022  14:41           619,109 pandas2.ipynb
16-11-2022  15:55           141,613 pandas3.ipynb
17-11-2022  13:14               588 pandas4.ipynb
21-11-2022  19:35           173,487 pandasday4.ipynb
08-11-2022  14:51             8,192 person.db
14-10-2022  11:56    <DIR>          plugins
02-12-2022  11:38    <DIR>          Postman
03-12-2023  10:34                16 priya.txt
07-05-2023  19:11    <DIR>          PycharmProjects
29-09-2022  08:46            10,630 python assignment 5.ipynb
08-10-2022  23:27            14,458 python basic assignment 6.ipynb
15-07-2023  12:52             7,374 python basic programming assignment 11.ipynb
20-07-2023  15:51             6,955 python basic programming assignment 12.ipynb
30-09-2022  18:26             6,317 python basic programming assignment 5.ipynb
07-10-2022  00:13             6,545 python basic programming assignment 6.ipynb
13-10-2022  16:11             4,776 python basic programming assignment 7.ipynb
23-09-2022  16:44             7,776 python basic programming assignment4.ipynb
11-07-2023  15:08             1,383 python programming assignment 10.ipynb
14-07-2023  10:20             9,645 python programming assignment 11.ipynb
04-07-2023  13:58             5,375 python programming assignment 8.ipynb
09-07-2023  17:13            10,556 python programming assignment 9.ipynb
22-08-2022  15:53             4,908 python programming assignment1.ipynb
21-09-2022  14:12             4,130 python programming assignment2.ipynb
22-09-2022  14:06            26,533 python programming assignment3.ipynb
08-11-2022  14:54             8,192 raj.db
08-10-2022  22:02                 9 raji.txt
06-10-2022  19:42                58 rama.txt
27-05-2021  04:27             1,526 readme.txt
21-06-2022  13:45            23,522 restart 20dec.ipynb
21-06-2022  17:07            21,171 restart 21dec.ipynb
17-06-2022  16:30            17,684 restart dec19.ipynb
14-10-2022  12:24                44 rfunmod1.py
13-10-2022  13:29               480 ritu.log
10-11-2022  19:13            14,905 Sales.csv
10-11-2022  19:36               201 sample.csv
10-11-2022  23:15               232 sample.xls.csv
07-12-2023  23:10           167,424 sample-xls-file-for-testing.xls
02-04-2023  19:10    <DIR>          Saved Games
30-11-2022  14:30    <DIR>          seaborn-data
02-04-2023  19:10    <DIR>          Searches
13-10-2022  13:35               904 seethu.log
27-05-2021  04:27               965 shortcuts.xml
08-11-2022  19:47            77,976 sql lite 08112022.ipynb
25-10-2022  14:40             8,079 sql part2.ipynb
22-10-2022  23:32             7,994 sql2.ipynb
20-09-2022  22:39           174,773 stylers.model.xml
30-09-2022  17:37             6,652 sudhasirqsadans.ipynb
30-06-2022  22:41               310 test.log
02-12-2023  11:55                 0 test.txt
13-10-2022  12:17                 4 test1
13-10-2022  11:53                22 test1.txt
30-07-2022  13:47               225 test11.py
30-06-2022  22:53               278 test2.log
27-06-2022  13:24                31 test2.txt
14-10-2022  11:29                 0 test3.py
28-06-2022  23:08                11 test3.txt
30-06-2022  16:50                 0 test43.txt
27-06-2022  21:30               551 test5.txt
07-05-2023  18:31               138 testu.py
14-10-2022  11:56    <DIR>          themes
28-02-2022  20:21            53,575 Untitled.ipynb
01-03-2022  14:37                72 Untitled1.ipynb
27-02-2023  14:30             1,679 Untitled10.ipynb
09-05-2023  10:29                72 Untitled11.ipynb
04-07-2023  13:54             8,651 Untitled12.ipynb
03-08-2023  10:33             3,443 Untitled13.ipynb
07-12-2023  21:37                72 Untitled14.ipynb
03-03-2022  15:56            36,553 Untitled2.ipynb
21-06-2022  15:32               588 Untitled3.ipynb
27-06-2022  22:55             5,082 Untitled4.ipynb
29-06-2022  00:49             5,617 Untitled5.ipynb
30-07-2022  12:48             1,518 Untitled6.ipynb
24-08-2022  17:18            18,874 Untitled7.ipynb
16-10-2022  10:53               588 Untitled8.ipynb
28-11-2022  14:32               796 Untitled9.ipynb
14-10-2022  11:56    <DIR>          updater
02-04-2023  19:10    <DIR>          Videos
             170 File(s)     15,591,770 bytes
              32 Dir(s)  414,916,407,296 bytes free

In [116]:
df1

,Rk,Player,Pos,Age,Tm,G,GS,MP,FG,FGA,...,FT%,ORB,DRB,TRB,AST,STL,BLK,TOV,PF,PTS
0,1,Quincy Acy,PF,24,NYK,68,22,1287,152,331,...,.784,79,222,301,68,27,22,60,147,398
1,2,Jordan Adams,SG,20,MEM,30,0,248,35,86,...,.609,9,19,28,16,16,7,14,24,94
2,3,Steven Adams,C,21,OKC,70,67,1771,217,399,...,.502,199,324,523,66,38,86,99,222,537
3,4,Jeff Adrien,PF,28,MIN,17,0,215,19,44,...,.579,23,54,77,15,4,9,9,30,60
4,5,Arron Afflalo,SG,29,TOT,78,72,2502,375,884,...,.843,27,220,247,129,41,7,116,167,1035
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
670,490,Thaddeus Young,PF,26,TOT,76,68,2434,451,968,...,.655,127,284,411,173,124,25,117,171,1071
671,490,Thaddeus Young,PF,26,MIN,48,48,1605,289,641,...,.682,75,170,245,135,86,17,75,115,685
672,490,Thaddeus Young,PF,26,BRK,28,20,829,162,327,...,.606,52,114,166,38,38,8,42,56,386
673,491,Cody Zeller,C,22,CHO,62,45,1487,172,373,...,.774,97,265,362,100,34,49,62,156,472
674,492,Tyler Zeller,C,25,BOS,82,59,1731,340,619,...,.823,146,319,465,113,18,52,76,205,833

In [1]:
import pandas as pd

In [ ]:
l=pd.read_html('https://stats.espncricinfo.com/ci/engine/records/averages/batting.html?class=3;id=6;type=team')

In [ ]:
len(l)

In [1]:
d="""{"name": "rajarajeswari",
"mailid":"raji@gmail.com",
"marks":[10,20,30,40,50],
"syllabus":["kidsneuron","techneuron","ineuron","robotics"]}"""

In [2]:
type(d)

str

In [3]:
# given data is in dict format but it is givving str as output
# because it is written in between double quotes

In [10]:
import json
import pandas as pd

In [11]:
result=json.loads(d)

In [12]:
type(result)

dict

In [13]:
result["name"]

'rajarajeswari'

In [14]:
# while using online json viewer we have to remove quotes

In [17]:
pd.DataFrame(result['syllabus'])

            0
0  kidsneuron
1  techneuron
2     ineuron
3    robotics

In [18]:
result['syllabus']

['kidsneuron', 'techneuron', 'ineuron', 'robotics']

In [19]:
d = {"packetType":"D","data":{"checkEngineLightFlag":"F","batteryVoltageStableTime":0,"batteryVoltageStable":"0","batteryVoltageOff":"12.42","batteryCrankParamTN":"-0.08","batteryCrankParamVN":"0.00","batteryCrankParamTP":"-0.08","batteryCrankParamVP":"0.00","batteryCrankParamTT":"-0.00008","batteryCrankParamV0":"0.00","batteryVoltageMaxOn":"13.05","batteryVoltageMinOn":"12.97","batteryVoltageMaxOff":"12.46","batteryVoltageMinOff":"12.36","batteryVoltageOnAverage":"13.02","engineLoadMax":"84","engineLoadAverage":"39.98","rpmMax":"3487","rpmAverage":"1431.29","gpsSpeedAverage":"21.99","vssMax":"53.44","vssAverage":"23.06","tcuTemperatureMin":"82.40","tcuTemperatureMax":"109.40","tcuTemperatureAverage":"104.87","coolantMin":"158.00","coolantMax":"188.60","coolantAverage":"180.20","packetStartLocal":1508143346000,"tripStartLocal":1508143346000,"milIndicator":"F","monitorsNotReady":0,"imei":"60DF5417","gatewayTs":1515613306592,"diagnosticTroubleCodeData":[],"diagnosticPidData":[[64768,47,100],[64768,1,517376],[64800,1,262144],[64768,5,125]]},"header":{"iwrapVer":"1.9.20","sourceSystem":"CDP","configVer":"1.1","oemName":"HUM","unitType":0,"cpVer":"7.50.1.9","igpsVer":"1.3.7","messageType":"Notification","pomVer":"1.0","headerVer":"V6","timestamp":0,"deviceType":"InDrive","visorVer":"1.4.35","transactionId":"53098471-7787-4160-94b3-cd69dcc70416","deviceSerialNo":"60DF5417","subOrganization":"HUM","organization":"HUM","imei":"60DF5417","operation":"Notification"}}

In [20]:
d1=d["data"]

In [21]:
d1

{'checkEngineLightFlag': 'F',
 'batteryVoltageStableTime': 0,
 'batteryVoltageStable': '0',
 'batteryVoltageOff': '12.42',
 'batteryCrankParamTN': '-0.08',
 'batteryCrankParamVN': '0.00',
 'batteryCrankParamTP': '-0.08',
 'batteryCrankParamVP': '0.00',
 'batteryCrankParamTT': '-0.00008',
 'batteryCrankParamV0': '0.00',
 'batteryVoltageMaxOn': '13.05',
 'batteryVoltageMinOn': '12.97',
 'batteryVoltageMaxOff': '12.46',
 'batteryVoltageMinOff': '12.36',
 'batteryVoltageOnAverage': '13.02',
 'engineLoadMax': '84',
 'engineLoadAverage': '39.98',
 'rpmMax': '3487',
 'rpmAverage': '1431.29',
 'gpsSpeedAverage': '21.99',
 'vssMax': '53.44',
 'vssAverage': '23.06',
 'tcuTemperatureMin': '82.40',
 'tcuTemperatureMax': '109.40',
 'tcuTemperatureAverage': '104.87',
 'coolantMin': '158.00',
 'coolantMax': '188.60',
 'coolantAverage': '180.20',
 'packetStartLocal': 1508143346000,
 'tripStartLocal': 1508143346000,
 'milIndicator': 'F',
 'monitorsNotReady': 0,
 'imei': '60DF5417',
 'gatewayTs': 1515613306592,
 'diagnosticTroubleCodeData': [],
 'diagnosticPidData': [[64768, 47, 100],
  [64768, 1, 517376],
  [64800, 1, 262144],
  [64768, 5, 125]]}

In [22]:
del d1['diagnosticTroubleCodeData']

In [23]:
d1

{'checkEngineLightFlag': 'F',
 'batteryVoltageStableTime': 0,
 'batteryVoltageStable': '0',
 'batteryVoltageOff': '12.42',
 'batteryCrankParamTN': '-0.08',
 'batteryCrankParamVN': '0.00',
 'batteryCrankParamTP': '-0.08',
 'batteryCrankParamVP': '0.00',
 'batteryCrankParamTT': '-0.00008',
 'batteryCrankParamV0': '0.00',
 'batteryVoltageMaxOn': '13.05',
 'batteryVoltageMinOn': '12.97',
 'batteryVoltageMaxOff': '12.46',
 'batteryVoltageMinOff': '12.36',
 'batteryVoltageOnAverage': '13.02',
 'engineLoadMax': '84',
 'engineLoadAverage': '39.98',
 'rpmMax': '3487',
 'rpmAverage': '1431.29',
 'gpsSpeedAverage': '21.99',
 'vssMax': '53.44',
 'vssAverage': '23.06',
 'tcuTemperatureMin': '82.40',
 'tcuTemperatureMax': '109.40',
 'tcuTemperatureAverage': '104.87',
 'coolantMin': '158.00',
 'coolantMax': '188.60',
 'coolantAverage': '180.20',
 'packetStartLocal': 1508143346000,
 'tripStartLocal': 1508143346000,
 'milIndicator': 'F',
 'monitorsNotReady': 0,
 'imei': '60DF5417',
 'gatewayTs': 1515613306592,
 'diagnosticPidData': [[64768, 47, 100],
  [64768, 1, 517376],
  [64800, 1, 262144],
  [64768, 5, 125]]}

In [24]:
pd.DataFrame(d1)

,checkEngineLightFlag,batteryVoltageStableTime,batteryVoltageStable,batteryVoltageOff,batteryCrankParamTN,batteryCrankParamVN,batteryCrankParamTP,batteryCrankParamVP,batteryCrankParamTT,batteryCrankParamV0,...,coolantMin,coolantMax,coolantAverage,packetStartLocal,tripStartLocal,milIndicator,monitorsNotReady,imei,gatewayTs,diagnosticPidData
0,F,0,0,12.42,-0.08,0.00,-0.08,0.00,-0.00008,0.00,...,158.00,188.60,180.20,1508143346000,1508143346000,F,0,60DF5417,1515613306592,"[64768, 47, 100]"
1,F,0,0,12.42,-0.08,0.00,-0.08,0.00,-0.00008,0.00,...,158.00,188.60,180.20,1508143346000,1508143346000,F,0,60DF5417,1515613306592,"[64768, 1, 517376]"
2,F,0,0,12.42,-0.08,0.00,-0.08,0.00,-0.00008,0.00,...,158.00,188.60,180.20,1508143346000,1508143346000,F,0,60DF5417,1515613306592,"[64800, 1, 262144]"
3,F,0,0,12.42,-0.08,0.00,-0.08,0.00,-0.00008,0.00,...,158.00,188.60,180.20,1508143346000,1508143346000,F,0,60DF5417,1515613306592,"[64768, 5, 125]"

In [25]:
pd.read_json("https://api.github.com/repos/pandas-dev/pandas/issues")

,url,repository_url,labels_url,comments_url,events_url,html_url,id,node_id,number,title,...,closed_at,author_association,active_lock_reason,body,reactions,timeline_url,performed_via_github_app,state_reason,draft,pull_request
0,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://github.com/pandas-dev/pandas/issues/56379,2031271223,I_kwDOAA0YD855Er03,56379,BUG: strings 'nan' istead of NaN values if pan...,...,NaT,NONE,NaN,### Pandas version checks\r\n\r\n- [X] I have ...,{'url': 'https://api.github.com/repos/pandas-d...,https://api.github.com/repos/pandas-dev/pandas...,NaN,None,NaN,NaN
1,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://github.com/pandas-dev/pandas/issues/56376,2030597935,I_kwDOAA0YD855CHcv,56376,BUG: Infinite recursion with outer merge on ca...,...,NaT,CONTRIBUTOR,NaN,### Pandas version checks\n\n- [X] I have chec...,{'url': 'https://api.github.com/repos/pandas-d...,https://api.github.com/repos/pandas-dev/pandas...,NaN,None,NaN,NaN
2,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://github.com/pandas-dev/pandas/pull/56375,2029896500,PR_kwDOAA0YD85hYD6S,56375,BLD: Refresh gitpod build files,...,NaT,MEMBER,NaN,- [ ] closes #xxxx (Replace xxxx with the GitH...,{'url': 'https://api.github.com/repos/pandas-d...,https://api.github.com/repos/pandas-dev/pandas...,NaN,None,0.0,{'url': 'https://api.github.com/repos/pandas-d...
3,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://github.com/pandas-dev/pandas/pull/56374,2029787247,PR_kwDOAA0YD85hXssM,56374,TYP: require_matching_freq,...,NaT,MEMBER,NaN,- [ ] closes #xxxx (Replace xxxx with the GitH...,{'url': 'https://api.github.com/repos/pandas-d...,https://api.github.com/repos/pandas-dev/pandas...,NaN,None,0.0,{'url': 'https://api.github.com/repos/pandas-d...
4,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://github.com/pandas-dev/pandas/pull/56373,2029780231,PR_kwDOAA0YD85hXrXx,56373,PERF: datetimelike addition,...,NaT,MEMBER,NaN,```\r\nIn [1]: import pandas as pd\r\n\r\nIn [...,{'url': 'https://api.github.com/repos/pandas-d...,https://api.github.com/repos/pandas-dev/pandas...,NaN,None,0.0,{'url': 'https://api.github.com/repos/pandas-d...
5,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://github.com/pandas-dev/pandas/pull/56371,2029558571,PR_kwDOAA0YD85hW9vj,56371,BUG: resample with ArrowDtype,...,NaT,MEMBER,NaN,- [x] closes #55989 (Replace xxxx with the Git...,{'url': 'https://api.github.com/repos/pandas-d...,https://api.github.com/repos/pandas-dev/pandas...,NaN,None,0.0,{'url': 'https://api.github.com/repos/pandas-d...
6,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://github.com/pandas-dev/pandas/pull/56370,2029450079,PR_kwDOAA0YD85hWldS,56370,BUG: rolling with datetime ArrowDtype,...,NaT,MEMBER,NaN,- [x] closes #55849 (Replace xxxx with the Git...,{'url': 'https://api.github.com/repos/pandas-d...,https://api.github.com/repos/pandas-dev/pandas...,NaN,None,0.0,{'url': 'https://api.github.com/repos/pandas-d...
7,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://github.com/pandas-dev/pandas/pull/56369,2029326891,PR_kwDOAA0YD85hWKcs,56369,Update nlargest nsmallest doc,...,NaT,NONE,NaN,- [x] closes #45041 (Replace xxxx with the Git...,{'url': 'https://api.github.com/repos/pandas-d...,https://api.github.com/repos/pandas-dev/pandas...,NaN,None,0.0,{'url': 'https://api.github.com/repos/pandas-d...
8,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://github.com/pandas-dev/pandas/issues/56367,2029137457,I_kwDOAA0YD8548i4x,56367,BUG: Merges erroneously match integer join key...,...,NaT,CONTRIBUTOR,NaN,### Pandas version checks\n\n- [X] I have chec...,{'url': 'https://api.github.com/repos/pandas-d...,https://api.github.com/repos/pandas-dev/pandas...,NaN,None,NaN,NaN
9,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://github.com/pandas-dev/pandas/issues/56366,2029132266,I_kwDOAA0YD8548hnq,56366,BUG: Can not select in MultiIndex with NaN,...,NaT,CONTRIBUTOR,NaN,### Pandas version checks\n\n- [X] I have chec...,{'url': 'https://api.github.com/repos/pandas-d...,https://api.github.com/repos/pandas-dev/pandas...,NaN,None,NaN,NaN
10,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://github.com/pandas-dev/pandas/pull/56365,2029129502,PR_kwDOAA0YD85hVfGM,56365,BUG: `concat` should keep series names unless ...,...,NaT,CONTRIBUTOR,NaN,- [x] closes #15047\r\n- [x] [Tests added and ...,{'url': 'https://api.github.com/repos/pandas-d...,https://api.github.com/repos/pandas-dev/pandas...,NaN,None,0.0,{'url': 'https://api.github.com/repos/pandas-d...
11,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://github.com/pandas-dev/pandas/pull/56362,2029052153,PR_kwDOAA0YD85hVOQ-,56362,Implicity convert series to DataFrame before d...,...,NaT,NONE,NaN,…(#56257)\r\n\r\n- [ ] closes #xxxx (Replace x...,{'url': 'https://api.github.com/repos/pandas-d...,https://api.github.com/repos/pandas-dev/pandas...,NaN,None,0.0,{'url': 'https://api.github.com/repos/pandas-d...
12,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://github.com/pandas-dev/pandas/issues/56361,2028991744,I_kwDOAA0YD8547_UA,56361,BUG: Can't read CSV with NaN values when usin...,...,NaT,NONE,NaN,### Pandas version checks\n\n- [X] I have chec...,{'url': 'https://api.github.com/repos/pandas-d...,https://api.github.com/repos/pandas-dev/pandas...,NaN,None,NaN,NaN
13,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://github.com/pandas-dev/pandas/pull/56360,2028379696,PR_kwDOAA0YD85hS5N-,56360,WIP BUG: Warning for incompatible type when t...,...,NaT,MEMBER,NaN,- [ ] closes #55990 (Replace xxxx with the Git...,{'url': 'https://api.github.com/repos/pandas-d...,https://api.github.com/repos/pandas-dev/pandas...,NaN,None,1.0,{'url': 'https://api.github.com/repos/pandas-d...
14,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://github.com/pandas-dev/pandas/issues/56359,2027757011,I_kwDOAA0YD8543R3T,56359,ENH: Type `pipe` with `ParamSpec`,...,NaT,CONTRIBUTOR,NaN,### Feature Type\r\n\r\n- [x] Adding new funct...,{'url': 'https://api.github.com/repos/pandas-d...,https://api.github.com/repos/pandas-dev/pandas...,NaN,None,NaN,NaN
15,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://github.com/pandas-dev/pandas/pull/56358,2027710152,PR_kwDOAA0YD85hQnm1,56358,BUG: Replaced ValueError exception with TypeEr...,...,NaT,NONE,NaN,\r\nReplaced ValueError exception with TypeErr...,{'url': 'https://api.github.com/repos/pandas-d...,https://api.github.com/repos/pandas-dev/pandas...,NaN,None,0.0,{'url': 'https://api.github.com/repos/pandas-d...
16,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://github.com/pandas-dev/pandas/pull/56357,2027682998,PR_kwDOAA0YD85hQhuW,56357,[WIP] BUG: unstack with sort=False fails when ...,...,NaT,NONE,NaN,Work in progress - I'll try to code these chan...,{'url': 'https://api.github.com/repos/pandas-d...,https://api.github.com/repos/pandas-dev/pandas...,NaN,None,1.0,{'url': 'https://api.github.com/repos/pandas-d...
17,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://github.com/pandas-dev/pandas/issues/56356,2027652255,I_kwDOAA0YD85424Sf,56356,ENH: Add kwargs to pandas.read_spss so that py...,...,NaT,NONE,NaN,### Feature Type\n\n- [X] Adding new functiona...,{'url': 'https://api.github.com/repos/pandas-d...,https://api.github.com/repos/pandas-dev/pandas...,NaN,None,NaN,NaN
18,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://github.com/pandas-dev/pandas/pull/56354,2027569048,PR_kwDOAA0YD85hQJmW,56354,"BUG DataFrame.update(self, other,join: str = ""...",...,NaT,NONE,NaN,- [ ] closes #55883 \r\n- [ ] [Tests added and...,{'url': 'https://api.github.com/repos/pandas-d...,https://api.github.com/repos/pandas-dev/pandas...,NaN,None,0.0,{'url': 'https://api.github.com/repos/pandas-d...
19,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://github.com/pandas-dev/pandas/issues/56353,2027483086,I_kwDOAA0YD8542O_O,56353,DOC: Add a FAQ item regarding a guaranteed in-...,...,NaT,NONE,NaN,### Pandas version checks\r\n\r\n- [X] I have ...,{'url': 'https://api.github.com/repos/pandas-d...,https://api.github.com/repos/pandas-dev/pandas...,NaN,None,NaN,NaN
20,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://github.com/pandas-dev/pandas/pull/56347,2027311214,PR_kwDOAA0YD85hPREF,56347,ENH: Implement Series.interpolate for ArrowDtype,...,NaT,MEMBER,NaN,- [ ] closes #56267 (Replace xxxx with the Git...,{'url': 'https://api.github.com/repos/pandas-d...,https://api.github.com/repos/pandas-dev/pandas...,NaN,None,0.0,{'url': 'https://api.github.com/repos/pandas-d...
21,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://github.com/pandas-dev/pandas/pull/56346,2027276733,PR_kwDOAA0YD85hPJdV,56346,DEPR: lowercase strings denoting freq for Week...,...,NaT,CONTRIBUTOR,NaN,xref #52064\r\n\r\ndeprecated lowercase string...,{'url': 'https://api.github.com/repos/pandas-d...,https://api.github.com/repos/pandas-dev/pandas...,NaN,None,1.0,{'url': 'https://api.github.com/repos/pandas-d...
22,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://github.com/pandas-dev/pandas/issues/56343,2026999022,I_kwDOAA0YD8540Yzu,56343,DOC: why is subtracting 1/1/1970 recommended o...,...,NaT,NONE,NaN,### Pandas version checks\n\n- [X] I have chec...,{'url': 'https://api.github.com/repos/pandas-d...,https://api.github.com/repos/pandas-dev/pandas...,NaN,None,NaN,NaN
23,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://github.com/pandas-dev/pandas/pull/56341,2025787253,PR_kwDOAA0YD85hJ_4j,56341,TST: Improved test coverage for Styler.bar err...,...,NaT,NONE,NaN,- [x] closes #56283 \r\n\r\n- Added two new ...,{'url': 'https://api.github.com/repos/pandas-d...,https://api.github.com/repos/pandas-dev/pandas...,NaN,None,0.0,{'url': 'https://api.github.com/repos/pandas-d...
24,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://github.com/pandas-dev/pandas/issues/56340,2025577797,I_kwDOAA0YD854u91F,56340,REGR: assert_frame_equal check_dtype=False no ...,...,NaT,MEMBER,NaN,"Noticed this from the geopandas CI, but on the...",{'url': 'https://api.github.com/repos/pandas-d...,https://api.github.com/repos/pandas-dev/pandas...,NaN,None,NaN,NaN
25,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://github.com/pandas-dev/pandas/issues/56337,2025123604,I_kwDOAA0YD854tO8U,56337,BUG: QST: `pd.read_html` gives tables with dup...,...,NaT,NONE,NaN,### Pandas version checks\n\n- [X] I have chec...,{'url': 'https://api.github.com/repos/pandas-d...,https://api.github.com/repos/pandas-dev/pandas...,NaN,None,NaN,NaN
26,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://github.com/pandas-dev/pandas/issues/56330,2024890907,I_kwDOAA0YD854sWIb,56330,BUG: df.mask with int df throws ValueError ins...,...,NaT,NONE,NaN,### Pandas version checks\n\n- [X] I have chec...,{'url': 'https://api.github.com/repos/pandas-d...,https://api.github.com/repos/pandas-dev/pandas...,NaN,reopened,NaN,NaN
27,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://github.com/pandas-dev/pandas/issues/56329,2024876292,I_kwDOAA0YD854sSkE,56329,BUG: AssertionError: Did not expect new dtype ...,...,NaT,CONTRIBUTOR,NaN,### Pandas version checks\r\n\r\n- [X] I have ...,{'url': 'https://api.github.com/repos/pandas-d...,https://api.github.com/repos/pandas-dev/pandas...,NaN,None,NaN,NaN
28,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://github.com/pandas-dev/pandas/pull/56327,2024546652,PR_kwDOAA0YD85hF14b,56327,Compiled pandas with -Wextra,...,NaT,MEMBER,NaN,Need to merge in https://github.com/pandas-dev...,{'url': 'https://api.github.com/repos/pandas-d...,https://api.github.com/repos/pandas-dev/pandas...,NaN,None,0.0,{'url': 'https://api.github.com/repos/pandas-d...
29,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://github.com/pandas-dev/pandas/issues/56322,2024195206,I_kwDOAA0YD854psSG,56322,"BUG: `Series` type as first item from list ,in...",...,NaT,NONE,NaN,### Pandas version checks\n\n- [X] I have chec...,{'url': 'https://api.github.com/repos/pandas-d...,https://api.github.com/repos/pandas-dev/pandas...,NaN,reopened,NaN,NaN

In [26]:
import requests
url="https://api.github.com/repos/pandas-dev/pandas/issues"

In [27]:
data=requests.get(url)

In [28]:
data

In [29]:
data1=data.json()

In [30]:
data1

[{'url': 'https://api.github.com/repos/pandas-dev/pandas/issues/56379',
  'repository_url': 'https://api.github.com/repos/pandas-dev/pandas',
  'labels_url': 'https://api.github.com/repos/pandas-dev/pandas/issues/56379/labels{/name}',
  'comments_url': 'https://api.github.com/repos/pandas-dev/pandas/issues/56379/comments',
  'events_url': 'https://api.github.com/repos/pandas-dev/pandas/issues/56379/events',
  'html_url': 'https://github.com/pandas-dev/pandas/issues/56379',
  'id': 2031271223,
  'node_id': 'I_kwDOAA0YD855Er03',
  'number': 56379,
  'title': "BUG: strings 'nan' istead of NaN values if pandas DataFrame is enlarged by setting values using DataFrame.at[] or DataFrame.loc[] with non-existent indexers",
  'user': {'login': 'EBenkler',
   'id': 16223042,
   'node_id': 'MDQ6VXNlcjE2MjIzMDQy',
   'avatar_url': 'https://avatars.githubusercontent.com/u/16223042?v=4',
   'gravatar_id': '',
   'url': 'https://api.github.com/users/EBenkler',
   'html_url': 'https://github.com/EBenkler',
   'followers_url': 'https://api.github.com/users/EBenkler/followers',
   'following_url': 'https://api.github.com/users/EBenkler/following{/other_user}',
   'gists_url': 'https://api.github.com/users/EBenkler/gists{/gist_id}',
   'starred_url': 'https://api.github.com/users/EBenkler/starred{/owner}{/repo}',
   'subscriptions_url': 'https://api.github.com/users/EBenkler/subscriptions',
   'organizations_url': 'https://api.github.com/users/EBenkler/orgs',
   'repos_url': 'https://api.github.com/users/EBenkler/repos',
   'events_url': 'https://api.github.com/users/EBenkler/events{/privacy}',
   'received_events_url': 'https://api.github.com/users/EBenkler/received_events',
   'type': 'User',
   'site_admin': False},
  'labels': [{'id': 76811,
    'node_id': 'MDU6TGFiZWw3NjgxMQ==',
    'url': 'https://api.github.com/repos/pandas-dev/pandas/labels/Bug',
    'name': 'Bug',
    'color': 'e10c02',
    'default': False,
    'description': None},
   {'id': 1954720290,
    'node_id': 'MDU6TGFiZWwxOTU0NzIwMjkw',
    'url': 'https://api.github.com/repos/pandas-dev/pandas/labels/Needs%20Triage',
    'name': 'Needs Triage',
    'color': '0052cc',
    'default': False,
    'description': 'Issue that has not been reviewed by a pandas team member'}],
  'state': 'open',
  'locked': False,
  'assignee': None,
  'assignees': [],
  'milestone': None,
  'comments': 0,
  'created_at': '2023-12-07T18:00:49Z',
  'updated_at': '2023-12-07T18:03:06Z',
  'closed_at': None,
  'author_association': 'NONE',
  'active_lock_reason': None,
  'body': '### Pandas version checks\r\n\r\n- [X] I have checked that this issue has not already been reported.\r\n\r\n- [X] I have confirmed this bug exists on the [latest version](https://pandas.pydata.org/docs/whatsnew/index.html) of pandas.\r\n\r\n- [ ] I have confirmed this bug exists on the [main branch](https://pandas.pydata.org/docs/dev/getting_started/install.html#installing-the-development-version-of-pandas) of pandas.\r\n\r\n\r\n### Reproducible Example\r\n\r\n```python\r\nimport pandas as pd\r\ndf= pd.DataFrame() # empty dataframe to append configuration strings\r\ndf.at[\'A\',\'1\']="first string"\r\ndf.at[\'B\',\'2\']="second string"\r\nprint(type(df.iat[1,0]))\r\nprint(type(df.iat[0,1]))\r\n# expected output:\r\n# <class \'float\'>\r\n# <class \'float\'>\r\n# actual output:\r\n# <class \'float\'>\r\n# <class \'numpy.str_\'>\r\n```\r\n\r\n\r\n### Issue Description\r\n\r\nWhen enlarging a DataFrame by setting values using DataFrame.at[] with non-existing indexers (see, e.g. [Setting with enlargement](https://pandas.pydata.org/docs/user_guide/indexing.html#setting-with-enlargement)), values at "unset" indices should be set to NaN, which has type <class \'float\'>. This used to work in older versions of Pandas, but now, the nan-values in the first row are set to the string \'nan\' with type <class \'numpy.str_\'>. See the minimal working example, which shows the same behaviour if at[] is substituted by loc[].\r\n\r\n### Expected Behavior\r\n\r\nThe above MWE should output:\r\n<class \'float\'>\r\n<class \'float\'>\r\nInstead, it outputs:\r\n<class \'float\'>\r\n<class \'numpy.str_\'>\r\nThis is because the nan value in \r\ndf.iat[0,1] or df.at[\'A\',\'2\'] is a string \'nan\' instead of float nan.\r\n\r\n### Installed Versions\r\n\r\n<details>\r\n\r\nINSTALLED VERSIONS\r\n------------------\r\ncommit              : 2a953cf80b77e4348bf50ed724f8abc0d814d9dd\r\npython              : 3.11.6.final.0\r\npython-bits         : 64\r\nOS                  : Windows\r\nOS-release          : 10\r\nVersion             : 10.0.19045\r\nmachine             : AMD64\r\nprocessor           : Intel64 Family 6 Model 42 Stepping 7, GenuineIntel\r\nbyteorder           : little\r\nLC_ALL              : None\r\nLANG                : en\r\nLOCALE              : de_DE.cp1252\r\n\r\npandas              : 2.1.3\r\nnumpy               : 1.26.0\r\npytz                : 2023.3.post1\r\ndateutil            : 2.8.2\r\nsetuptools          : 68.2.2\r\npip                 : 23.3.1\r\nCython              : None\r\npytest              : None\r\nhypothesis          : None\r\nsphinx              : 7.2.6\r\nblosc               : None\r\nfeather             : None\r\nxlsxwriter          : None\r\nlxml.etree          : None\r\nhtml5lib            : None\r\npymysql             : None\r\npsycopg2            : None\r\njinja2              : 3.1.2\r\nIPython             : 8.17.2\r\npandas_datareader   : None\r\nbs4                 : 4.12.2\r\nbottleneck          : None\r\ndataframe-api-compat: None\r\nfastparquet         : None\r\nfsspec              : 2023.10.0\r\ngcsfs               : None\r\nmatplotlib          : 3.8.1\r\nnumba               : None\r\nnumexpr             : 2.8.7\r\nodfpy               : None\r\nopenpyxl            : None\r\npandas_gbq          : None\r\npyarrow             : 14.0.1\r\npyreadstat          : None\r\npyxlsb              : None\r\ns3fs                : None\r\nscipy               : 1.11.3\r\nsqlalchemy          : None\r\ntables              : 3.9.1\r\ntabulate            : None\r\nxarray              : None\r\nxlrd                : None\r\nzstandard           : None\r\ntzdata              : 2023.3\r\nqtpy                : 2.4.1\r\npyqt5               : None\r\n</details>\r\n',
  'reactions': {'url': 'https://api.github.com/repos/pandas-dev/pandas/issues/56379/reactions',
   'total_count': 0,
   '+1': 0,
   '-1': 0,
   'laugh': 0,
   'hooray': 0,
   'confused': 0,
   'heart': 0,
   'rocket': 0,
   'eyes': 0},
  'timeline_url': 'https://api.github.com/repos/pandas-dev/pandas/issues/56379/timeline',
  'performed_via_github_app': None,
  'state_reason': None},
 {'url': 'https://api.github.com/repos/pandas-dev/pandas/issues/56376',
  'repository_url': 'https://api.github.com/repos/pandas-dev/pandas',
  'labels_url': 'https://api.github.com/repos/pandas-dev/pandas/issues/56376/labels{/name}',
  'comments_url': 'https://api.github.com/repos/pandas-dev/pandas/issues/56376/comments',
  'events_url': 'https://api.github.com/repos/pandas-dev/pandas/issues/56376/events',
  'html_url': 'https://github.com/pandas-dev/pandas/issues/56376',
  'id': 2030597935,
  'node_id': 'I_kwDOAA0YD855CHcv',
  'number': 56376,
  'title': 'BUG: Infinite recursion with outer merge on categorical key column if left and right dtypes are mismatching non-nullable numeric kinds',
  'user': {'login': 'wence-',
   'id': 1126981,
   'node_id': 'MDQ6VXNlcjExMjY5ODE=',
   'avatar_url': 'https://avatars.githubusercontent.com/u/1126981?v=4',
   'gravatar_id': '',
   'url': 'https://api.github.com/users/wence-',
   'html_url': 'https://github.com/wence-',
   'followers_url': 'https://api.github.com/users/wence-/followers',
   'following_url': 'https://api.github.com/users/wence-/following{/other_user}',
   'gists_url': 'https://api.github.com/users/wence-/gists{/gist_id}',
   'starred_url': 'https://api.github.com/users/wence-/starred{/owner}{/repo}',
   'subscriptions_url': 'https://api.github.com/users/wence-/subscriptions',
   'organizations_url': 'https://api.github.com/users/wence-/orgs',
   'repos_url': 'https://api.github.com/users/wence-/repos',
   'events_url': 'https://api.github.com/users/wence-/events{/privacy}',
   'received_events_url': 'https://api.github.com/users/wence-/received_events',
   'type': 'User',
   'site_admin': False},
  'labels': [{'id': 76811,
    'node_id': 'MDU6TGFiZWw3NjgxMQ==',
    'url': 'https://api.github.com/repos/pandas-dev/pandas/labels/Bug',
    'name': 'Bug',
    'color': 'e10c02',
    'default': False,
    'description': None},
   {'id': 1954720290,
    'node_id': 'MDU6TGFiZWwxOTU0NzIwMjkw',
    'url': 'https://api.github.com/repos/pandas-dev/pandas/labels/Needs%20Triage',
    'name': 'Needs Triage',
    'color': '0052cc',
    'default': False,
    'description': 'Issue that has not been reviewed by a pandas team member'}],
  'state': 'open',
  'locked': False,
  'assignee': None,
  'assignees': [],
  'milestone': None,
  'comments': 0,
  'created_at': '2023-12-07T11:51:14Z',
  'updated_at': '2023-12-07T11:51:14Z',
  'closed_at': None,
  'author_association': 'CONTRIBUTOR',
  'active_lock_reason': None,
  'body': '### Pandas version checks\n\n- [X] I have checked that this issue has not already been reported.\n\n- [X] I have confirmed this bug exists on the [latest version](https://pandas.pydata.org/docs/whatsnew/index.html) of pandas.\n\n- [X] I have confirmed this bug exists on the [main branch](https://pandas.pydata.org/docs/dev/getting_started/install.html#installing-the-development-version-of-pandas) of pandas.\n\n\n### Reproducible Example\n\n```python\nimport pandas as pd\r\nimport numpy as np\r\nlt = pd.CategoricalDtype(categories=np.asarray([1, 2, 3], dtype="int64"))\r\nrt = pd.CategoricalDtype(categories=np.asarray([1, 2, 3], dtype="float64"))\r\nleft = pd.DataFrame({"key": pd.Series([1, 2], dtype=lt)})\r\nright = pd.DataFrame({"key": pd.Series([1, 3], dtype=rt)})\r\nleft.merge(right, on="key", how="outer")\n```\n\n\n### Issue Description\n\n```\r\n  [...]\r\n  File "<stdin>", line 1, in <module>\r\n  File "/home/wence/Documents/src/rapids/third-party/pandas/pandas/core/frame.py", line 10737, in merge\r\n    return merge(\r\n  File "/home/wence/Documents/src/rapids/third-party/pandas/pandas/core/reshape/merge.py", line 185, in merge\r\n    return op.get_result(copy=copy)\r\n  File "/home/wence/Documents/src/rapids/third-party/pandas/pandas/core/reshape/merge.py", line 897, in get_result\r\n    self._maybe_add_join_keys(result, left_indexer, right_indexer)\r\n  File "/home/wence/Documents/src/rapids/third-party/pandas/pandas/core/reshape/merge.py", line 1076, in _maybe_add_join_keys\r\n    key_col = Index(lvals).where(~mask_left, rvals)\r\n  File "/home/wence/Documents/src/rapids/third-party/pandas/pandas/core/indexes/base.py", line 5237, in where\r\n    return self.putmask(~cond, other)\r\n  File "/home/wence/Documents/src/rapids/third-party/pandas/pandas/core/indexes/base.py", line 5493, in putmask\r\n    return self.astype(dtype).putmask(mask, value)\r\n  File "/home/wence/Documents/src/rapids/third-party/pandas/pandas/core/indexes/base.py", line 5493, in putmask\r\n    return self.astype(dtype).putmask(mask, value)\r\n  File "/home/wence/Documents/src/rapids/third-party/pandas/pandas/core/indexes/base.py", line 5493, in putmask\r\n    return self.astype(dtype).putmask(mask, value)\r\n  [Previous line repeated 984 more times]\r\n  File "/home/wence/Documents/src/rapids/third-party/pandas/pandas/core/indexes/base.py", line 1057, in astype\r\n    return self.copy() if copy else self\r\n  File "/home/wence/Documents/src/rapids/third-party/pandas/pandas/core/indexes/base.py", line 1259, in copy\r\n    name = self._validate_names(name=name, deep=deep)[0]\r\n  File "/home/wence/Documents/src/rapids/third-party/pandas/pandas/core/indexes/base.py", line 1701, in _validate_names\r\n    validate_all_hashable(*new_names, error_name=f"{type(self).__name__}.name")\r\n  File "/home/wence/Documents/src/rapids/third-party/pandas/pandas/core/dtypes/common.py", line 1575, in validate_all_hashable\r\n    if not all(is_hashable(arg) for arg in args):\r\n  File "/home/wence/Documents/src/rapids/third-party/pandas/pandas/core/dtypes/common.py", line 1575, in <genexpr>\r\n    if not all(is_hashable(arg) for arg in args):\r\n  File "/home/wence/Documents/src/rapids/third-party/pandas/pandas/core/dtypes/inference.py", line 366, in is_hashable\r\n    hash(obj)\r\nRecursionError: maximum recursion depth exceeded while calling a Python object\r\n```\n\n### Expected Behavior\n\nI would expect this to complete, probably behaving as if the left and right key columns were of type int64 and float64. I would also accept raising.\n\n### Installed Versions\n\n<details>\r\n\r\n```\r\nINSTALLED VERSIONS\r\n------------------\r\ncommit                : b864b8eb54605124827e6af84aa7fbc816cfc1e0\r\npython                : 3.10.12.final.0\r\npython-bits           : 64\r\nOS                    : Linux\r\nOS-release            : 6.2.0-37-generic\r\nVersion               : #38~22.04.1-Ubuntu SMP PREEMPT_DYNAMIC Thu Nov  2 18:01:13 UTC 2\r\nmachine               : x86_64\r\nprocessor             : x86_64\r\nbyteorder             : little\r\nLC_ALL                : None\r\nLANG                  : en_GB.UTF-8\r\nLOCALE                : en_GB.UTF-8\r\n\r\npandas                : 2.1.0.dev0+1414.gb864b8eb54\r\nnumpy                 : 1.24.4\r\npytz                  : 2023.3\r\ndateutil              : 2.8.2\r\nsetuptools            : 67.7.2\r\npip                   : 23.2.1\r\nCython                : 3.0.0\r\npytest                : 7.4.0\r\nhypothesis            : 6.82.2\r\nsphinx                : 6.2.1\r\nblosc                 : None\r\nfeather               : None\r\nxlsxwriter            : 3.1.2\r\nlxml.etree            : 4.9.3\r\nhtml5lib              : 1.1\r\npymysql               : 1.4.6\r\npsycopg2              : 2.9.6\r\njinja2                : 3.1.2\r\nIPython               : 8.14.0\r\npandas_datareader     : None\r\nadbc-driver-postgresql: None\r\nadbc-driver-sqlite    : None\r\nbs4                   : 4.12.2\r\nbottleneck            : 1.3.7\r\ndataframe-api-compat  : None\r\nfastparquet           : 2023.7.0\r\nfsspec                : 2023.6.0\r\ngcsfs                 : 2023.6.0\r\nmatplotlib            : 3.7.2\r\nnumba                 : 0.57.1\r\nnumexpr               : 2.8.4\r\nodfpy                 : None\r\nopenpyxl              : 3.1.2\r\npandas_gbq            : None\r\npyarrow               : 12.0.1\r\npyreadstat            : 1.2.2\r\npython-calamine       : None\r\npyxlsb                : 1.0.10\r\ns3fs                  : 2023.6.0\r\nscipy                 : 1.11.1\r\nsqlalchemy            : 2.0.19\r\ntables                : 3.8.0\r\ntabulate              : 0.9.0\r\nxarray                : 2023.7.0\r\nxlrd                  : 2.0.1\r\nzstandard             : 0.19.0\r\ntzdata                : 2023.3\r\nqtpy                  : 2.4.0\r\npyqt5                 : None\r\n```\r\n\r\n</details>\r\n',
  'reactions': {'url': 'https://api.github.com/repos/pandas-dev/pandas/issues/56376/reactions',
   'total_count': 0,
   '+1': 0,
   '-1': 0,
   'laugh': 0,
   'hooray': 0,
   'confused': 0,
   'heart': 0,
   'rocket': 0,
   'eyes': 0},
  'timeline_url': 'https://api.github.com/repos/pandas-dev/pandas/issues/56376/timeline',
  'performed_via_github_app': None,
  'state_reason': None},
 {'url': 'https://api.github.com/repos/pandas-dev/pandas/issues/56375',
  'repository_url': 'https://api.github.com/repos/pandas-dev/pandas',
  'labels_url': 'https://api.github.com/repos/pandas-dev/pandas/issues/56375/labels{/name}',
  'comments_url': 'https://api.github.com/repos/pandas-dev/pandas/issues/56375/comments',
  'events_url': 'https://api.github.com/repos/pandas-dev/pandas/issues/56375/events',
  'html_url': 'https://github.com/pandas-dev/pandas/pull/56375',
  'id': 2029896500,
  'node_id': 'PR_kwDOAA0YD85hYD6S',
  'number': 56375,
  'title': 'BLD: Refresh gitpod build files',
  'user': {'login': 'lithomas1',
   'id': 47963215,
   'node_id': 'MDQ6VXNlcjQ3OTYzMjE1',
   'avatar_url': 'https://avatars.githubusercontent.com/u/47963215?v=4',
   'gravatar_id': '',
   'url': 'https://api.github.com/users/lithomas1',
   'html_url': 'https://github.com/lithomas1',
   'followers_url': 'https://api.github.com/users/lithomas1/followers',
   'following_url': 'https://api.github.com/users/lithomas1/following{/other_user}',
   'gists_url': 'https://api.github.com/users/lithomas1/gists{/gist_id}',
   'starred_url': 'https://api.github.com/users/lithomas1/starred{/owner}{/repo}',
   'subscriptions_url': 'https://api.github.com/users/lithomas1/subscriptions',
   'organizations_url': 'https://api.github.com/users/lithomas1/orgs',
   'repos_url': 'https://api.github.com/users/lithomas1/repos',
   'events_url': 'https://api.github.com/users/lithomas1/events{/privacy}',
   'received_events_url': 'https://api.github.com/users/lithomas1/received_events',
   'type': 'User',
   'site_admin': False},
  'labels': [{'id': 48070600,
    'node_id': 'MDU6TGFiZWw0ODA3MDYwMA==',
    'url': 'https://api.github.com/repos/pandas-dev/pandas/labels/CI',
    'name': 'CI',
    'color': 'a2bca7',
    'default': False,
    'description': 'Continuous Integration'}],
  'state': 'open',
  'locked': False,
  'assignee': None,
  'assignees': [],
  'milestone': None,
  'comments': 0,
  'created_at': '2023-12-07T04:52:20Z',
  'updated_at': '2023-12-07T17:16:55Z',
  'closed_at': None,
  'author_association': 'MEMBER',
  'active_lock_reason': None,
  'draft': False,
  'pull_request': {'url': 'https://api.github.com/repos/pandas-dev/pandas/pulls/56375',
   'html_url': 'https://github.com/pandas-dev/pandas/pull/56375',
   'diff_url': 'https://github.com/pandas-dev/pandas/pull/56375.diff',
   'patch_url': 'https://github.com/pandas-dev/pandas/pull/56375.patch',
   'merged_at': None},
  'body': '- [ ] closes #xxxx (Replace xxxx with the GitHub issue number)\r\n- [ ] [Tests added and passed](https://pandas.pydata.org/pandas-docs/dev/development/contributing_codebase.html#writing-tests) if fixing a bug or adding a new feature\r\n- [ ] All [code checks passed](https://pandas.pydata.org/pandas-docs/dev/development/contributing_codebase.html#pre-commit).\r\n- [ ] Added [type annotations](https://pandas.pydata.org/pandas-docs/dev/development/contributing_codebase.html#type-hints) to new arguments/methods/functions.\r\n- [ ] Added an entry in the latest `doc/source/whatsnew/vX.X.X.rst` file if fixing a bug or adding a new feature.\r\n',
  'reactions': {'url': 'https://api.github.com/repos/pandas-dev/pandas/issues/56375/reactions',
   'total_count': 0,
   '+1': 0,
   '-1': 0,
   'laugh': 0,
   'hooray': 0,
   'confused': 0,
   'heart': 0,
   'rocket': 0,
   'eyes': 0},
  'timeline_url': 'https://api.github.com/repos/pandas-dev/pandas/issues/56375/timeline',
  'performed_via_github_app': None,
  'state_reason': None},
 {'url': 'https://api.github.com/repos/pandas-dev/pandas/issues/56374',
  'repository_url': 'https://api.github.com/repos/pandas-dev/pandas',
  'labels_url': 'https://api.github.com/repos/pandas-dev/pandas/issues/56374/labels{/name}',
  'comments_url': 'https://api.github.com/repos/pandas-dev/pandas/issues/56374/comments',
  'events_url': 'https://api.github.com/repos/pandas-dev/pandas/issues/56374/events',
  'html_url': 'https://github.com/pandas-dev/pandas/pull/56374',
  'id': 2029787247,
  'node_id': 'PR_kwDOAA0YD85hXssM',
  'number': 56374,
  'title': 'TYP: require_matching_freq',
  'user': {'login': 'jbrockmendel',
   'id': 8078968,
   'node_id': 'MDQ6VXNlcjgwNzg5Njg=',
   'avatar_url': 'https://avatars.githubusercontent.com/u/8078968?v=4',
   'gravatar_id': '',
   'url': 'https://api.github.com/users/jbrockmendel',
   'html_url': 'https://github.com/jbrockmendel',
   'followers_url': 'https://api.github.com/users/jbrockmendel/followers',

In [31]:
len(data1)

30

In [33]:
for i in range(len(data1)):
    print(data1[i]['user']['id'])

16223042
1126981
47963215
8078968
8078968
10647082
10647082
33153091
1126981
332746
124158982
66105100
37619875
33491632
30049606
72032381
64710719
17667690
132615348
30159171
10647082
91160475
4811862
144291871
1020496
45640029
149019786
6614121
609873
63046380

In [34]:
data1

[{'url': 'https://api.github.com/repos/pandas-dev/pandas/issues/56379',
  'repository_url': 'https://api.github.com/repos/pandas-dev/pandas',
  'labels_url': 'https://api.github.com/repos/pandas-dev/pandas/issues/56379/labels{/name}',
  'comments_url': 'https://api.github.com/repos/pandas-dev/pandas/issues/56379/comments',
  'events_url': 'https://api.github.com/repos/pandas-dev/pandas/issues/56379/events',
  'html_url': 'https://github.com/pandas-dev/pandas/issues/56379',
  'id': 2031271223,
  'node_id': 'I_kwDOAA0YD855Er03',
  'number': 56379,
  'title': "BUG: strings 'nan' istead of NaN values if pandas DataFrame is enlarged by setting values using DataFrame.at[] or DataFrame.loc[] with non-existent indexers",
  'user': {'login': 'EBenkler',
   'id': 16223042,
   'node_id': 'MDQ6VXNlcjE2MjIzMDQy',
   'avatar_url': 'https://avatars.githubusercontent.com/u/16223042?v=4',
   'gravatar_id': '',
   'url': 'https://api.github.com/users/EBenkler',
   'html_url': 'https://github.com/EBenkler',
   'followers_url': 'https://api.github.com/users/EBenkler/followers',
   'following_url': 'https://api.github.com/users/EBenkler/following{/other_user}',
   'gists_url': 'https://api.github.com/users/EBenkler/gists{/gist_id}',
   'starred_url': 'https://api.github.com/users/EBenkler/starred{/owner}{/repo}',
   'subscriptions_url': 'https://api.github.com/users/EBenkler/subscriptions',
   'organizations_url': 'https://api.github.com/users/EBenkler/orgs',
   'repos_url': 'https://api.github.com/users/EBenkler/repos',
   'events_url': 'https://api.github.com/users/EBenkler/events{/privacy}',
   'received_events_url': 'https://api.github.com/users/EBenkler/received_events',
   'type': 'User',
   'site_admin': False},
  'labels': [{'id': 76811,
    'node_id': 'MDU6TGFiZWw3NjgxMQ==',
    'url': 'https://api.github.com/repos/pandas-dev/pandas/labels/Bug',
    'name': 'Bug',
    'color': 'e10c02',
    'default': False,
    'description': None},
   {'id': 1954720290,
    'node_id': 'MDU6TGFiZWwxOTU0NzIwMjkw',
    'url': 'https://api.github.com/repos/pandas-dev/pandas/labels/Needs%20Triage',
    'name': 'Needs Triage',
    'color': '0052cc',
    'default': False,
    'description': 'Issue that has not been reviewed by a pandas team member'}],
  'state': 'open',
  'locked': False,
  'assignee': None,
  'assignees': [],
  'milestone': None,
  'comments': 0,
  'created_at': '2023-12-07T18:00:49Z',
  'updated_at': '2023-12-07T18:03:06Z',
  'closed_at': None,
  'author_association': 'NONE',
  'active_lock_reason': None,
  'body': '### Pandas version checks\r\n\r\n- [X] I have checked that this issue has not already been reported.\r\n\r\n- [X] I have confirmed this bug exists on the [latest version](https://pandas.pydata.org/docs/whatsnew/index.html) of pandas.\r\n\r\n- [ ] I have confirmed this bug exists on the [main branch](https://pandas.pydata.org/docs/dev/getting_started/install.html#installing-the-development-version-of-pandas) of pandas.\r\n\r\n\r\n### Reproducible Example\r\n\r\n```python\r\nimport pandas as pd\r\ndf= pd.DataFrame() # empty dataframe to append configuration strings\r\ndf.at[\'A\',\'1\']="first string"\r\ndf.at[\'B\',\'2\']="second string"\r\nprint(type(df.iat[1,0]))\r\nprint(type(df.iat[0,1]))\r\n# expected output:\r\n# <class \'float\'>\r\n# <class \'float\'>\r\n# actual output:\r\n# <class \'float\'>\r\n# <class \'numpy.str_\'>\r\n```\r\n\r\n\r\n### Issue Description\r\n\r\nWhen enlarging a DataFrame by setting values using DataFrame.at[] with non-existing indexers (see, e.g. [Setting with enlargement](https://pandas.pydata.org/docs/user_guide/indexing.html#setting-with-enlargement)), values at "unset" indices should be set to NaN, which has type <class \'float\'>. This used to work in older versions of Pandas, but now, the nan-values in the first row are set to the string \'nan\' with type <class \'numpy.str_\'>. See the minimal working example, which shows the same behaviour if at[] is substituted by loc[].\r\n\r\n### Expected Behavior\r\n\r\nThe above MWE should output:\r\n<class \'float\'>\r\n<class \'float\'>\r\nInstead, it outputs:\r\n<class \'float\'>\r\n<class \'numpy.str_\'>\r\nThis is because the nan value in \r\ndf.iat[0,1] or df.at[\'A\',\'2\'] is a string \'nan\' instead of float nan.\r\n\r\n### Installed Versions\r\n\r\n<details>\r\n\r\nINSTALLED VERSIONS\r\n------------------\r\ncommit              : 2a953cf80b77e4348bf50ed724f8abc0d814d9dd\r\npython              : 3.11.6.final.0\r\npython-bits         : 64\r\nOS                  : Windows\r\nOS-release          : 10\r\nVersion             : 10.0.19045\r\nmachine             : AMD64\r\nprocessor           : Intel64 Family 6 Model 42 Stepping 7, GenuineIntel\r\nbyteorder           : little\r\nLC_ALL              : None\r\nLANG                : en\r\nLOCALE              : de_DE.cp1252\r\n\r\npandas              : 2.1.3\r\nnumpy               : 1.26.0\r\npytz                : 2023.3.post1\r\ndateutil            : 2.8.2\r\nsetuptools          : 68.2.2\r\npip                 : 23.3.1\r\nCython              : None\r\npytest              : None\r\nhypothesis          : None\r\nsphinx              : 7.2.6\r\nblosc               : None\r\nfeather             : None\r\nxlsxwriter          : None\r\nlxml.etree          : None\r\nhtml5lib            : None\r\npymysql             : None\r\npsycopg2            : None\r\njinja2              : 3.1.2\r\nIPython             : 8.17.2\r\npandas_datareader   : None\r\nbs4                 : 4.12.2\r\nbottleneck          : None\r\ndataframe-api-compat: None\r\nfastparquet         : None\r\nfsspec              : 2023.10.0\r\ngcsfs               : None\r\nmatplotlib          : 3.8.1\r\nnumba               : None\r\nnumexpr             : 2.8.7\r\nodfpy               : None\r\nopenpyxl            : None\r\npandas_gbq          : None\r\npyarrow             : 14.0.1\r\npyreadstat          : None\r\npyxlsb              : None\r\ns3fs                : None\r\nscipy               : 1.11.3\r\nsqlalchemy          : None\r\ntables              : 3.9.1\r\ntabulate            : None\r\nxarray              : None\r\nxlrd                : None\r\nzstandard           : None\r\ntzdata              : 2023.3\r\nqtpy                : 2.4.1\r\npyqt5               : None\r\n</details>\r\n',
  'reactions': {'url': 'https://api.github.com/repos/pandas-dev/pandas/issues/56379/reactions',
   'total_count': 0,
   '+1': 0,
   '-1': 0,
   'laugh': 0,
   'hooray': 0,
   'confused': 0,
   'heart': 0,
   'rocket': 0,
   'eyes': 0},
  'timeline_url': 'https://api.github.com/repos/pandas-dev/pandas/issues/56379/timeline',
  'performed_via_github_app': None,
  'state_reason': None},
 {'url': 'https://api.github.com/repos/pandas-dev/pandas/issues/56376',
  'repository_url': 'https://api.github.com/repos/pandas-dev/pandas',
  'labels_url': 'https://api.github.com/repos/pandas-dev/pandas/issues/56376/labels{/name}',
  'comments_url': 'https://api.github.com/repos/pandas-dev/pandas/issues/56376/comments',
  'events_url': 'https://api.github.com/repos/pandas-dev/pandas/issues/56376/events',
  'html_url': 'https://github.com/pandas-dev/pandas/issues/56376',
  'id': 2030597935,
  'node_id': 'I_kwDOAA0YD855CHcv',
  'number': 56376,
  'title': 'BUG: Infinite recursion with outer merge on categorical key column if left and right dtypes are mismatching non-nullable numeric kinds',
  'user': {'login': 'wence-',
   'id': 1126981,
   'node_id': 'MDQ6VXNlcjExMjY5ODE=',
   'avatar_url': 'https://avatars.githubusercontent.com/u/1126981?v=4',
   'gravatar_id': '',
   'url': 'https://api.github.com/users/wence-',
   'html_url': 'https://github.com/wence-',
   'followers_url': 'https://api.github.com/users/wence-/followers',
   'following_url': 'https://api.github.com/users/wence-/following{/other_user}',
   'gists_url': 'https://api.github.com/users/wence-/gists{/gist_id}',
   'starred_url': 'https://api.github.com/users/wence-/starred{/owner}{/repo}',
   'subscriptions_url': 'https://api.github.com/users/wence-/subscriptions',
   'organizations_url': 'https://api.github.com/users/wence-/orgs',
   'repos_url': 'https://api.github.com/users/wence-/repos',
   'events_url': 'https://api.github.com/users/wence-/events{/privacy}',
   'received_events_url': 'https://api.github.com/users/wence-/received_events',
   'type': 'User',
   'site_admin': False},
  'labels': [{'id': 76811,
    'node_id': 'MDU6TGFiZWw3NjgxMQ==',
    'url': 'https://api.github.com/repos/pandas-dev/pandas/labels/Bug',
    'name': 'Bug',
    'color': 'e10c02',
    'default': False,
    'description': None},
   {'id': 1954720290,
    'node_id': 'MDU6TGFiZWwxOTU0NzIwMjkw',
    'url': 'https://api.github.com/repos/pandas-dev/pandas/labels/Needs%20Triage',
    'name': 'Needs Triage',
    'color': '0052cc',
    'default': False,
    'description': 'Issue that has not been reviewed by a pandas team member'}],
  'state': 'open',
  'locked': False,
  'assignee': None,
  'assignees': [],
  'milestone': None,
  'comments': 0,
  'created_at': '2023-12-07T11:51:14Z',
  'updated_at': '2023-12-07T11:51:14Z',
  'closed_at': None,
  'author_association': 'CONTRIBUTOR',
  'active_lock_reason': None,
  'body': '### Pandas version checks\n\n- [X] I have checked that this issue has not already been reported.\n\n- [X] I have confirmed this bug exists on the [latest version](https://pandas.pydata.org/docs/whatsnew/index.html) of pandas.\n\n- [X] I have confirmed this bug exists on the [main branch](https://pandas.pydata.org/docs/dev/getting_started/install.html#installing-the-development-version-of-pandas) of pandas.\n\n\n### Reproducible Example\n\n```python\nimport pandas as pd\r\nimport numpy as np\r\nlt = pd.CategoricalDtype(categories=np.asarray([1, 2, 3], dtype="int64"))\r\nrt = pd.CategoricalDtype(categories=np.asarray([1, 2, 3], dtype="float64"))\r\nleft = pd.DataFrame({"key": pd.Series([1, 2], dtype=lt)})\r\nright = pd.DataFrame({"key": pd.Series([1, 3], dtype=rt)})\r\nleft.merge(right, on="key", how="outer")\n```\n\n\n### Issue Description\n\n```\r\n  [...]\r\n  File "<stdin>", line 1, in <module>\r\n  File "/home/wence/Documents/src/rapids/third-party/pandas/pandas/core/frame.py", line 10737, in merge\r\n    return merge(\r\n  File "/home/wence/Documents/src/rapids/third-party/pandas/pandas/core/reshape/merge.py", line 185, in merge\r\n    return op.get_result(copy=copy)\r\n  File "/home/wence/Documents/src/rapids/third-party/pandas/pandas/core/reshape/merge.py", line 897, in get_result\r\n    self._maybe_add_join_keys(result, left_indexer, right_indexer)\r\n  File "/home/wence/Documents/src/rapids/third-party/pandas/pandas/core/reshape/merge.py", line 1076, in _maybe_add_join_keys\r\n    key_col = Index(lvals).where(~mask_left, rvals)\r\n  File "/home/wence/Documents/src/rapids/third-party/pandas/pandas/core/indexes/base.py", line 5237, in where\r\n    return self.putmask(~cond, other)\r\n  File "/home/wence/Documents/src/rapids/third-party/pandas/pandas/core/indexes/base.py", line 5493, in putmask\r\n    return self.astype(dtype).putmask(mask, value)\r\n  File "/home/wence/Documents/src/rapids/third-party/pandas/pandas/core/indexes/base.py", line 5493, in putmask\r\n    return self.astype(dtype).putmask(mask, value)\r\n  File "/home/wence/Documents/src/rapids/third-party/pandas/pandas/core/indexes/base.py", line 5493, in putmask\r\n    return self.astype(dtype).putmask(mask, value)\r\n  [Previous line repeated 984 more times]\r\n  File "/home/wence/Documents/src/rapids/third-party/pandas/pandas/core/indexes/base.py", line 1057, in astype\r\n    return self.copy() if copy else self\r\n  File "/home/wence/Documents/src/rapids/third-party/pandas/pandas/core/indexes/base.py", line 1259, in copy\r\n    name = self._validate_names(name=name, deep=deep)[0]\r\n  File "/home/wence/Documents/src/rapids/third-party/pandas/pandas/core/indexes/base.py", line 1701, in _validate_names\r\n    validate_all_hashable(*new_names, error_name=f"{type(self).__name__}.name")\r\n  File "/home/wence/Documents/src/rapids/third-party/pandas/pandas/core/dtypes/common.py", line 1575, in validate_all_hashable\r\n    if not all(is_hashable(arg) for arg in args):\r\n  File "/home/wence/Documents/src/rapids/third-party/pandas/pandas/core/dtypes/common.py", line 1575, in <genexpr>\r\n    if not all(is_hashable(arg) for arg in args):\r\n  File "/home/wence/Documents/src/rapids/third-party/pandas/pandas/core/dtypes/inference.py", line 366, in is_hashable\r\n    hash(obj)\r\nRecursionError: maximum recursion depth exceeded while calling a Python object\r\n```\n\n### Expected Behavior\n\nI would expect this to complete, probably behaving as if the left and right key columns were of type int64 and float64. I would also accept raising.\n\n### Installed Versions\n\n<details>\r\n\r\n```\r\nINSTALLED VERSIONS\r\n------------------\r\ncommit                : b864b8eb54605124827e6af84aa7fbc816cfc1e0\r\npython                : 3.10.12.final.0\r\npython-bits           : 64\r\nOS                    : Linux\r\nOS-release            : 6.2.0-37-generic\r\nVersion               : #38~22.04.1-Ubuntu SMP PREEMPT_DYNAMIC Thu Nov  2 18:01:13 UTC 2\r\nmachine               : x86_64\r\nprocessor             : x86_64\r\nbyteorder             : little\r\nLC_ALL                : None\r\nLANG                  : en_GB.UTF-8\r\nLOCALE                : en_GB.UTF-8\r\n\r\npandas                : 2.1.0.dev0+1414.gb864b8eb54\r\nnumpy                 : 1.24.4\r\npytz                  : 2023.3\r\ndateutil              : 2.8.2\r\nsetuptools            : 67.7.2\r\npip                   : 23.2.1\r\nCython                : 3.0.0\r\npytest                : 7.4.0\r\nhypothesis            : 6.82.2\r\nsphinx                : 6.2.1\r\nblosc                 : None\r\nfeather               : None\r\nxlsxwriter            : 3.1.2\r\nlxml.etree            : 4.9.3\r\nhtml5lib              : 1.1\r\npymysql               : 1.4.6\r\npsycopg2              : 2.9.6\r\njinja2                : 3.1.2\r\nIPython               : 8.14.0\r\npandas_datareader     : None\r\nadbc-driver-postgresql: None\r\nadbc-driver-sqlite    : None\r\nbs4                   : 4.12.2\r\nbottleneck            : 1.3.7\r\ndataframe-api-compat  : None\r\nfastparquet           : 2023.7.0\r\nfsspec                : 2023.6.0\r\ngcsfs                 : 2023.6.0\r\nmatplotlib            : 3.7.2\r\nnumba                 : 0.57.1\r\nnumexpr               : 2.8.4\r\nodfpy                 : None\r\nopenpyxl              : 3.1.2\r\npandas_gbq            : None\r\npyarrow               : 12.0.1\r\npyreadstat            : 1.2.2\r\npython-calamine       : None\r\npyxlsb                : 1.0.10\r\ns3fs                  : 2023.6.0\r\nscipy                 : 1.11.1\r\nsqlalchemy            : 2.0.19\r\ntables                : 3.8.0\r\ntabulate              : 0.9.0\r\nxarray                : 2023.7.0\r\nxlrd                  : 2.0.1\r\nzstandard             : 0.19.0\r\ntzdata                : 2023.3\r\nqtpy                  : 2.4.0\r\npyqt5                 : None\r\n```\r\n\r\n</details>\r\n',
  'reactions': {'url': 'https://api.github.com/repos/pandas-dev/pandas/issues/56376/reactions',
   'total_count': 0,
   '+1': 0,
   '-1': 0,
   'laugh': 0,
   'hooray': 0,
   'confused': 0,
   'heart': 0,
   'rocket': 0,
   'eyes': 0},
  'timeline_url': 'https://api.github.com/repos/pandas-dev/pandas/issues/56376/timeline',
  'performed_via_github_app': None,
  'state_reason': None},
 {'url': 'https://api.github.com/repos/pandas-dev/pandas/issues/56375',
  'repository_url': 'https://api.github.com/repos/pandas-dev/pandas',
  'labels_url': 'https://api.github.com/repos/pandas-dev/pandas/issues/56375/labels{/name}',
  'comments_url': 'https://api.github.com/repos/pandas-dev/pandas/issues/56375/comments',
  'events_url': 'https://api.github.com/repos/pandas-dev/pandas/issues/56375/events',
  'html_url': 'https://github.com/pandas-dev/pandas/pull/56375',
  'id': 2029896500,
  'node_id': 'PR_kwDOAA0YD85hYD6S',
  'number': 56375,
  'title': 'BLD: Refresh gitpod build files',
  'user': {'login': 'lithomas1',
   'id': 47963215,
   'node_id': 'MDQ6VXNlcjQ3OTYzMjE1',
   'avatar_url': 'https://avatars.githubusercontent.com/u/47963215?v=4',
   'gravatar_id': '',
   'url': 'https://api.github.com/users/lithomas1',
   'html_url': 'https://github.com/lithomas1',
   'followers_url': 'https://api.github.com/users/lithomas1/followers',
   'following_url': 'https://api.github.com/users/lithomas1/following{/other_user}',
   'gists_url': 'https://api.github.com/users/lithomas1/gists{/gist_id}',
   'starred_url': 'https://api.github.com/users/lithomas1/starred{/owner}{/repo}',
   'subscriptions_url': 'https://api.github.com/users/lithomas1/subscriptions',
   'organizations_url': 'https://api.github.com/users/lithomas1/orgs',
   'repos_url': 'https://api.github.com/users/lithomas1/repos',
   'events_url': 'https://api.github.com/users/lithomas1/events{/privacy}',
   'received_events_url': 'https://api.github.com/users/lithomas1/received_events',
   'type': 'User',
   'site_admin': False},
  'labels': [{'id': 48070600,
    'node_id': 'MDU6TGFiZWw0ODA3MDYwMA==',
    'url': 'https://api.github.com/repos/pandas-dev/pandas/labels/CI',
    'name': 'CI',
    'color': 'a2bca7',
    'default': False,
    'description': 'Continuous Integration'}],
  'state': 'open',
  'locked': False,
  'assignee': None,
  'assignees': [],
  'milestone': None,
  'comments': 0,
  'created_at': '2023-12-07T04:52:20Z',
  'updated_at': '2023-12-07T17:16:55Z',
  'closed_at': None,
  'author_association': 'MEMBER',
  'active_lock_reason': None,
  'draft': False,
  'pull_request': {'url': 'https://api.github.com/repos/pandas-dev/pandas/pulls/56375',
   'html_url': 'https://github.com/pandas-dev/pandas/pull/56375',
   'diff_url': 'https://github.com/pandas-dev/pandas/pull/56375.diff',
   'patch_url': 'https://github.com/pandas-dev/pandas/pull/56375.patch',
   'merged_at': None},
  'body': '- [ ] closes #xxxx (Replace xxxx with the GitHub issue number)\r\n- [ ] [Tests added and passed](https://pandas.pydata.org/pandas-docs/dev/development/contributing_codebase.html#writing-tests) if fixing a bug or adding a new feature\r\n- [ ] All [code checks passed](https://pandas.pydata.org/pandas-docs/dev/development/contributing_codebase.html#pre-commit).\r\n- [ ] Added [type annotations](https://pandas.pydata.org/pandas-docs/dev/development/contributing_codebase.html#type-hints) to new arguments/methods/functions.\r\n- [ ] Added an entry in the latest `doc/source/whatsnew/vX.X.X.rst` file if fixing a bug or adding a new feature.\r\n',
  'reactions': {'url': 'https://api.github.com/repos/pandas-dev/pandas/issues/56375/reactions',
   'total_count': 0,
   '+1': 0,
   '-1': 0,
   'laugh': 0,
   'hooray': 0,
   'confused': 0,
   'heart': 0,
   'rocket': 0,
   'eyes': 0},
  'timeline_url': 'https://api.github.com/repos/pandas-dev/pandas/issues/56375/timeline',
  'performed_via_github_app': None,
  'state_reason': None},
 {'url': 'https://api.github.com/repos/pandas-dev/pandas/issues/56374',
  'repository_url': 'https://api.github.com/repos/pandas-dev/pandas',
  'labels_url': 'https://api.github.com/repos/pandas-dev/pandas/issues/56374/labels{/name}',
  'comments_url': 'https://api.github.com/repos/pandas-dev/pandas/issues/56374/comments',
  'events_url': 'https://api.github.com/repos/pandas-dev/pandas/issues/56374/events',
  'html_url': 'https://github.com/pandas-dev/pandas/pull/56374',
  'id': 2029787247,
  'node_id': 'PR_kwDOAA0YD85hXssM',
  'number': 56374,
  'title': 'TYP: require_matching_freq',
  'user': {'login': 'jbrockmendel',
   'id': 8078968,
   'node_id': 'MDQ6VXNlcjgwNzg5Njg=',
   'avatar_url': 'https://avatars.githubusercontent.com/u/8078968?v=4',
   'gravatar_id': '',
   'url': 'https://api.github.com/users/jbrockmendel',
   'html_url': 'https://github.com/jbrockmendel',
   'followers_url': 'https://api.github.com/users/jbrockmendel/followers',

In [35]:
df2=pd.DataFrame(data1,columns=['id','url','repository_url','labels_url','user'])

In [36]:
df2.to_csv('json_res.csv')

In [37]:
ls

 Volume in drive C is Windows-SSD
 Volume Serial Number is BA08-EA00

 Directory of C:\Users\91903

08-12-2023  00:02    <DIR>          .
02-04-2023  19:05    <DIR>          ..
31-07-2022  11:32    <DIR>          .astropy
31-07-2022  11:13    <DIR>          .conda
30-11-2022  14:28    <DIR>          .cufflinks
08-05-2023  16:03    <DIR>          .idea
07-12-2023  21:38    <DIR>          .ipynb_checkpoints
21-02-2022  17:38    <DIR>          .ipython
05-03-2022  10:37    <DIR>          .jupyter
31-07-2022  11:40    <DIR>          .matplotlib
03-12-2023  18:07    <DIR>          __pycache__
08-10-2022  22:23            21,198 15th jan exception handling part1.ipynb
26-02-2023  16:06             6,880 16th jan logging.ipynb
25-08-2022  18:29            56,638 18th dec practice.ipynb
18-08-2023  10:20            63,220 19th dec practice.ipynb
11-09-2023  17:09         4,672,436 2023 20dec for loop  and while ipynb.ipynb
11-09-2023  21:28            23,182 2023 21dec ipynb.ipynb
14-09-2023  20:19            30,516 2023 23dec, 8th jan function ipynb.ipynb
01-06-2023  15:09             9,891 2023 6th feb sql day2.ipynb
11-09-2023  13:41            46,294 2023 dec18th set tuple dict ipynb part2.ipynb
11-09-2023  12:26            25,571 2023 dec19th new ipynb if else.ipynb
10-09-2023  22:01            68,837 2023 dec5th str,list new ipynb.ipynb
07-05-2023  19:28           110,238 2023 modules and pycharm.ipynb
11-05-2023  16:37            11,034 2023 sql part 1 feb5th.ipynb
18-08-2023  11:24            21,293 20thdec practice.ipynb
09-04-2022  15:17            23,165 21st dec practice.ipynb
14-10-2022  16:05           100,700 22jan module discussion.ipynb
14-10-2022  17:38             5,648 22jan oops concept.ipynb
30-07-2022  13:00                 0 22jan.py
30-07-2022  13:15                29 22jan1.py
26-06-2022  21:49            22,964 23decrestart.ipynb
11-04-2022  17:05            33,103 23rd dec practice.ipynb
19-10-2022  14:31             8,048 23rd jan oops concept.ipynb
24-08-2022  17:17            34,953 29jan oops.ipynb
25-06-2022  23:46            18,529 8th jan .ipynb
16-10-2022  22:12            38,125 8th jan practice.ipynb
06-10-2022  19:59           105,942 9th jan iterator,generator and filesystem.ipynb
27-06-2022  21:47            69,372 9thjanpractice.ipynb
07-05-2023  18:05                 0 akhil.py
21-02-2022  16:16    <DIR>          anaconda3
02-12-2022  12:49             1,089 API FLASK1.ipynb
04-07-2023  11:44            14,141 Assignment 8.ipynb
04-07-2023  12:15             4,535 Assignment 9.ipynb
28-02-2022  14:55             8,732 Assignment1.ipynb
08-05-2022  18:10            15,719 assignment2.ipynb
22-08-2022  11:36            15,644 Assignment4.ipynb
14-10-2022  11:56    <DIR>          autoCompletion
16-11-2022  14:49           461,474 bank.csv
16-11-2022  14:46           461,474 bank.xls
23-09-2022  02:00             1,007 change.log
02-04-2023  19:10    <DIR>          Contacts
17-01-2022  06:13             4,843 contextMenu.xml
15-11-2022  11:25             5,845 cricket.csv
10-11-2022  11:31             1,560 datastax.ipynb
07-12-2023  21:49               355 day.csv
03-05-2022  12:58            55,145 dec 5th practice.ipynb
25-08-2022  11:55            41,712 dec 5th practice2.ipynb
16-08-2023  13:02            23,803 dec4th practice.ipynb
07-12-2023  22:30               577 Details.csv
01-04-2022  17:58    <DIR>          Documents
07-12-2023  23:11    <DIR>          Downloads
24-04-2023  13:09                22 enapple.ini
13-10-2022  14:04            94,633 exception part2 and logging.ipynb
30-06-2022  21:18            35,344 excpthndlng2.ipynb
28-06-2022  23:07            12,467 exhndlng1.ipynb
02-04-2023  19:10    <DIR>          Favorites
05-10-2022  18:07            89,207 function dec 23rd class practice.ipynb
14-10-2022  11:56    <DIR>          functionList
14-10-2022  12:37               131 funmod1.py
14-10-2022  12:22                 0 funmod2.py
14-10-2022  12:53                94 funmod3.py
14-10-2022  13:00                40 funmod4.py
29-11-2022  22:57         3,078,946 graph 1.ipynb
30-11-2022  17:59         1,789,919 graph2.ipynb
01-12-2023  15:52            56,367 htd 8th jan.ipynb
28-11-2023  15:16                72 hyd 1.ipynb
02-12-2023  18:51            21,791 hyd 15th jan.ipynb
03-12-2023  14:53            51,859 hyd 16th jan.ipynb
30-11-2023  11:30            33,145 hyd 20th dec.ipynb
30-11-2023  20:07            18,848 hyd 21st dec.ipynb
01-12-2023  15:50            28,293 hyd 23rd dec.ipynb
02-12-2023  14:24           140,622 hyd 9th jan.ipynb
29-11-2023  11:37            80,734 hyd dec18th.ipynb
08-12-2023  00:02           764,379 hyd feb 26th pandas.ipynb
03-12-2023  18:14            29,972 hyd jan22nd.ipynb
02-12-2023  15:15           122,373 hyd practice book.ipynb
29-11-2023  14:02            44,090 hyd19th dec.ipynb
03-12-2023  18:13                 0 hydmodule1.py
02-12-2023  13:48               725 hydpara.txt
03-12-2023  14:47             1,074 hydtest.log
02-12-2023  18:18                19 hydtest.txt
02-12-2023  11:59                38 hydtest1.txt
03-12-2023  14:17               567 hydtest2.log
03-12-2023  14:42                 0 hydtest3.log
31-07-2022  12:59            41,601 jan22practice.ipynb
08-11-2022  15:10            12,288 joindb.db
08-11-2022  15:20             8,720 joindb.db-journal
08-12-2023  00:03            34,778 json_res.csv
28-05-2022  07:17           350,341 langs.model.xml
15-08-2021  05:50            35,500 LICENSE
06-10-2022  19:56               147 life.txt
02-04-2023  19:10    <DIR>          Links
14-10-2022  11:56    <DIR>          localization
06-10-2022  19:27             1,934 mahesh.txt
06-10-2022  18:50                51 manasa.txt
13-10-2022  13:52                 0 meethu.log
07-05-2023  18:20               180 mini.py
07-05-2023  17:55                 0 mod1.py
07-05-2023  18:12               130 mod2.py
07-05-2023  17:54                 0 module.py
14-10-2022  11:39                 0 module2.py
27-10-2022  12:23             5,444 mongodb.ipynb
02-04-2023  19:10    <DIR>          Music
30-07-2022  14:06               213 my_module.py
25-10-2022  14:40            10,208 mysql class1.ipynb
07-12-2023  23:32            78,962 NBA.csv
03-12-2023  17:57    <DIR>          notepadplus
05-12-2021  09:58                 0 nppLogNulContentCorruptionIssue.xml
25-09-2022  23:30           232,984 NppShell_06.dll
23-11-2022  17:51            50,763 numpy.ipynb
02-04-2023  19:08    <DIR>          OneDrive
31-07-2022  19:10             5,529 oops basic 22jan.ipynb
01-08-2022  15:53            11,638 oops jan23.ipynb
22-11-2022  21:35           107,440 pandas and numpy.ipynb
10-11-2022  23:34           128,025 pandas1.ipynb
15-11-2022  14:41           619,109 pandas2.ipynb
16-11-2022  15:55           141,613 pandas3.ipynb
17-11-2022  13:14               588 pandas4.ipynb
21-11-2022  19:35           173,487 pandasday4.ipynb
08-11-2022  14:51             8,192 person.db
14-10-2022  11:56    <DIR>          plugins
02-12-2022  11:38    <DIR>          Postman
03-12-2023  10:34                16 priya.txt
07-05-2023  19:11    <DIR>          PycharmProjects
29-09-2022  08:46            10,630 python assignment 5.ipynb
08-10-2022  23:27            14,458 python basic assignment 6.ipynb
15-07-2023  12:52             7,374 python basic programming assignment 11.ipynb
20-07-2023  15:51             6,955 python basic programming assignment 12.ipynb
30-09-2022  18:26             6,317 python basic programming assignment 5.ipynb
07-10-2022  00:13             6,545 python basic programming assignment 6.ipynb
13-10-2022  16:11             4,776 python basic programming assignment 7.ipynb
23-09-2022  16:44             7,776 python basic programming assignment4.ipynb
11-07-2023  15:08             1,383 python programming assignment 10.ipynb
14-07-2023  10:20             9,645 python programming assignment 11.ipynb
04-07-2023  13:58             5,375 python programming assignment 8.ipynb
09-07-2023  17:13            10,556 python programming assignment 9.ipynb
22-08-2022  15:53             4,908 python programming assignment1.ipynb
21-09-2022  14:12             4,130 python programming assignment2.ipynb
22-09-2022  14:06            26,533 python programming assignment3.ipynb
08-11-2022  14:54             8,192 raj.db
08-10-2022  22:02                 9 raji.txt
06-10-2022  19:42                58 rama.txt
27-05-2021  04:27             1,526 readme.txt
21-06-2022  13:45            23,522 restart 20dec.ipynb
21-06-2022  17:07            21,171 restart 21dec.ipynb
17-06-2022  16:30            17,684 restart dec19.ipynb
14-10-2022  12:24                44 rfunmod1.py
13-10-2022  13:29               480 ritu.log
10-11-2022  19:13            14,905 Sales.csv
10-11-2022  19:36               201 sample.csv
10-11-2022  23:15               232 sample.xls.csv
07-12-2023  23:10           167,424 sample-xls-file-for-testing.xls
02-04-2023  19:10    <DIR>          Saved Games
30-11-2022  14:30    <DIR>          seaborn-data
02-04-2023  19:10    <DIR>          Searches
13-10-2022  13:35               904 seethu.log
27-05-2021  04:27               965 shortcuts.xml
08-11-2022  19:47            77,976 sql lite 08112022.ipynb
25-10-2022  14:40             8,079 sql part2.ipynb
22-10-2022  23:32             7,994 sql2.ipynb
20-09-2022  22:39           174,773 stylers.model.xml
30-09-2022  17:37             6,652 sudhasirqsadans.ipynb
30-06-2022  22:41               310 test.log
02-12-2023  11:55                 0 test.txt
13-10-2022  12:17                 4 test1
13-10-2022  11:53                22 test1.txt
30-07-2022  13:47               225 test11.py
30-06-2022  22:53               278 test2.log
27-06-2022  13:24                31 test2.txt
14-10-2022  11:29                 0 test3.py
28-06-2022  23:08                11 test3.txt
30-06-2022  16:50                 0 test43.txt
27-06-2022  21:30               551 test5.txt
07-05-2023  18:31               138 testu.py
14-10-2022  11:56    <DIR>          themes
28-02-2022  20:21            53,575 Untitled.ipynb
01-03-2022  14:37                72 Untitled1.ipynb
27-02-2023  14:30             1,679 Untitled10.ipynb
09-05-2023  10:29                72 Untitled11.ipynb
04-07-2023  13:54             8,651 Untitled12.ipynb
03-08-2023  10:33             3,443 Untitled13.ipynb
07-12-2023  21:37                72 Untitled14.ipynb
03-03-2022  15:56            36,553 Untitled2.ipynb
21-06-2022  15:32               588 Untitled3.ipynb
27-06-2022  22:55             5,082 Untitled4.ipynb
29-06-2022  00:49             5,617 Untitled5.ipynb
30-07-2022  12:48             1,518 Untitled6.ipynb
24-08-2022  17:18            18,874 Untitled7.ipynb
16-10-2022  10:53               588 Untitled8.ipynb
28-11-2022  14:32               796 Untitled9.ipynb
14-10-2022  11:56    <DIR>          updater
02-04-2023  19:10    <DIR>          Videos
             170 File(s)     16,100,015 bytes
              32 Dir(s)  414,910,029,824 bytes free

In [41]:
import pandas as pd

In [42]:
df=pd.read_csv('https://raw.githubusercontent.com/datasciencedojo/datasets/master/titanic.csv')

URLError: <urlopen error [WinError 10054] An existing connection was forcibly closed by the remote host>